### ISSUE TITLE
Make the windows installer a module itself

### ISSUE THREAD

**Issue by stefanjudis** [loopline-systems/electron-builder#1]
The MacOS dmg is created by appdmg. 

Removing the logic for dealing with nsi and putting it into another module, would make electron-builder more testable and maintainable.

See - https://github.com/stefanjudis/winstaller

**Comment by justinmchase** [comment]
I'm looking at trying to get it to run on windows right now. It seems like moving `appdmg` to an optionalDependency allows it to install successfully on windows. I don't think that moving it to a separate project is necessary. Hopefully will have a pull request shortly.

**Comment by stefanjudis** [comment]
Yeah it's more about putting complexity out to make the project easier to maintain. 

But yeah - let's see where your PR brings us first. :)

**Comment by havenchyk** [comment]
Is there any updates here?

**Comment by stefanjudis** [comment]
Let's keep it like it is for now here. :)

**Comment by havenchyk** [comment]
But what about the topic? Is there any result?

**Comment by stefanjudis** [comment]
Well... yeah could be.
It might make sense to have a nsis installer module in npm out there.
But I have not the time to do that currently and `electron-builder` is running smoothly as it is right now. :)

**Comment by justinmchase** [comment]
@havenchyk The update was to make `appdmg` into an optional dependency and to then fix it up to work on windows. This now works on windows, but you do have to install `nsis` separately first and make sure its in your path.

**Comment by havenchyk** [comment]
@justinmchase but what is better for windows: `nsis` or `nuget`? AFAIK, `nuget` is newer.

**Comment by justinmchase** [comment]
I haven't been apart of that discussion. As far as I know `nuget` doesn't build installers. But I've been out of the `.net` loop for a while so that could be a new thing. But anyway, I think you'd have to install nuget separately too. No?

**Comment by havenchyk** [comment]
@justinmchase I'm just a newbie here and would like to create `.msi` and `.dmg` files for my app, nothing more :)

**Comment by justinmchase** [comment]
@havenchyk Well you're in the right place then I think. I don't think NuGet creates .msi's. nsis does, which is why you need it installed. This package essentially just drives nsis with a consistent cross-platform node-friendly api. But nsis does all the work.
