### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by sindresorhus** [loopline-systems/electron-builder#10]
Some quick things I noticed:

- `macos` => `osx`. It used to be Mac OS X, but now it's just OS X. It's never been Mac OS.
- Instead of a `packager.json` file, why not just put it in package.json under a `packager` field?
- The config is very verbose: https://github.com/loopline-systems/electron-builder#how-we-use-it-so-far It needs better defaults. Make it as easy as possible to do normal things like package for all platforms and rather have more advanced verbose config available if needed, which most probably don't need. You're also duplicating a lot of metadata from `electron-packager`. Maybe we need a simple wrapper tool for all these modules?

**Comment by stefanjudis** [comment]
@sindresorhus 

Thanks for the feedback. :bowtie: 

> macos => osx. It used to be Mac OS X, but now it's just OS X. It's never been Mac OS.

Agree, will change it.

> Instead of a packager.json file, why not just put it in package.json under a packager field?

I'm not sure about this one to be honest.

> It needs better defaults. Make it as easy as possible to do normal things like package for all platforms and rather have more advanced verbose config available if needed, which most probably don't need. 

Totally agree on defaults ( #12 ).

> You're also duplicating a lot of metadata from electron-packager. Maybe we need a simple wrapper tool for all these modules?

Which duplication do you mean?

**Comment by sindresorhus** [comment]
> Which duplication do you mean in detail?

This is a lot of config. Wish it were a lot simpler by default to package and create installer for all platforms. Maybe some kind of abstraction module for the simple case, or even just better defaults.

```
"build": "npm run clean && npm run build:macos && npm run build:win",
    "build:macos": "npm run clean:macos && electron-packager ./app \"Loopline Systems\" --out=dist/macos --platform=darwin --arch=x64 --version=0.25.3 --icon=assets/macos/loopline.icns",
    "build:win": "npm run clean:win && electron-packager ./app \"Loopline Systems\" --out=dist/win --platform=win32 --arch=ia32 --version=0.25.3 --icon=assets/win/icon.ico",

    "pack": "npm run pack:macos && npm run pack:win",
    "pack:macos": "npm run build:macos && electron-builder \"dist/macos/Loopline Systems.app\" --platform=macos --out=\"dist/macos\" --config=packager.json",
    "pack:win": "npm run build:win && electron-builder \"dist/win/Loopline Systems-win32\" --platform=win --out=\"dist/win\" --config=packager.json"
```

**Comment by krainboltgreene** [comment]
So I'm deploying a application with both electron builder and packager. So far it's been OK, I agree with the points made here though. There's a lot of work that could really be done inside a config (json) file that's being done inside command line parameters (or js api).

**Comment by stefanjudis** [comment]
Thanks for feedback. :bowtie: 

I totally agree on that.

First I want to provide better defaults. #12
Simplifying the command exposed via CLI would be the next step then. #13

Detailed wishes and ideas are welcome. ;)

**Comment by krainboltgreene** [comment]
Yeah, I'm going to be doing some PR's pretty soon. builder saved me a LOT of time, I want to give back.

**Comment by stefanjudis** [comment]
Sounds great!

Thanks. :bowtie:

**Comment by havenchyk** [comment]
Is there any unresolved issues here? 

@sindresorhus thanks for your feedback!

**Comment by stefanjudis** [comment]
We've got issues for these... so let's close here. :)
