### ISSUE TITLE
Error: Could not load config file

### ISSUE THREAD

**Issue by baikon** [loopline-systems/electron-builder#102]
I have a builder.json and set --config=builder.json but get "Error: Could not load config file" when running electron-builder. Anyone else have this issue?

using electron-builder 2.5.0
error is thrown at:
node_modules/electron-builder/index.js:63:26
node_modules/electron-builder/cli.js:36:9

**Comment by havenchyk** [comment]
@baikon could you please try to use absolute path and not relative? 

Also it would be grateful if you could provide an example of your full config.

**Comment by stefanjudis** [comment]
> could you please try to use absolute path and not relative?

Relative paths should work though. :)

@baikon https://github.com/loopline-systems/electron-builder/blob/master/CONTRIBUTING.md :)

**Comment by stefanjudis** [comment]
`electron-builder \"/Users/stefan/share/win/Blocky-win32-ia32\" --platform=win --out=\"/Users/stefan/share/win\" --config=packager.json"` runs fine here.

**Comment by baikon** [comment]
Ah, sure thing:
node version: v0.12.7
npm version: 3.33.10

i am using the example config.json from the readme

i just tried using absolute urls and running:
```
electron-builder \"/Users/baikon/dist/public/electronApp-darwin-x64\" --platform=osx --out=\"/Users/baikon/dist/public/installers\" --config=builder.json
```

log:
```
- Running electron-builder 2.5.0
/Users/baikon/dist/public/node_modules/electron-builder/cli.js:40
    throw error;
          ^
Error: Could not load config file
    at Object.Builder.build (/Users/baikon/dist/public/node_modules/electron-builder/index.js:66:26)
    at Object.<anonymous> (/Users/baikon/dist/public/node_modules/electron-builder/cli.js:36:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by stefanjudis** [comment]
And the file is definitely there - relatively to the directory you're firing `electron-builder`?

Can you log the path here and make sure it's not a mistake on your side?

`(/Users/baikon/dist/public/node_modules/electron-builder/index.js:66:26)`

**Comment by baikon** [comment]
ok, i found that it's throwing a syntax error in the sample config, it doesn't like the "// optional" comments for some reason

**Comment by stefanjudis** [comment]
> it doesn't like the "// optional" comments for some reason

That's not valid JSON... We should remove these maybe. ;)

Can you maybe file an issue giving a short version of what you did and requesting that the error message was misleading? :)  A PR would also be great of course. :)

**Comment by baikon** [comment]
sure thing, thanks for your attention and responses today - much appreciated.
