### ISSUE TITLE
Confusing readme

### ISSUE THREAD

**Issue by havenchyk** [loopline-systems/electron-builder#107]
> The project has currently only been executed on OS X machines. Any support or help for Windows is welcome.

Are you sure about it? I'm using on windows and linux and everything works fine. Is it just an old information?

**Comment by stefanjudis** [comment]
Outdated... Should be removed as people use it now on linux and windows.

**Comment by havenchyk** [comment]
@stefanjudis offtop, but just to let you know :) https://github.com/brave/browser-laptop/blob/master/package.json#L83

**Comment by stefanjudis** [comment]
@havenchyk nice... thanks for letting me know. We only have to switch the windows stuff to squirrel and then we're pretty good i think. :)

**Comment by havenchyk** [comment]
Yep, support of squirrel will be very useful.
