### ISSUE TITLE
EPERM error when compiling on Windows

### ISSUE THREAD

**Issue by eveningkid** [loopline-systems/electron-builder#119]
Hey everyone,

First, thank you for having created this tool! I guess it helps a bunch of people out there! :smile: 

I'm trying to create an executable under __Windows__ but it seems I get an error everytime. Here it is:

```
- Running electron-builder 2.6.0
- Starting creation of installer for ´win
fs.js:932
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: EPERM: operation not permitted, unlink 'C:\Users\ARNAUD~1\AppData\Local\Temp\icon.ico'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:932:18)
    at copyFileSync (C:\Users\****\AppData\Roaming\npm\node_modules\electron-builder\node_modules\fs-extra\lib\copy-sync\copy-file-sync.js:13:10)
    at Object.copySync (C:\Users\****\AppData\Roaming\npm\node_modules\electron-builder\node_modules\fs-extra\lib\copy-sync\copy-sync.js:31:7)
    at _copyAssetsToTmpFolder (C:\Users\****\AppData\Roaming\npm\node_modules\electron-builder\lib\win.js:129:6)
    at Object.WinBuilder.build (C:\Users\****\AppData\Roaming\npm\node_modules\electron-builder\lib\win.js:47:5)
    at Object.Builder.build (C:\Users\****\AppData\Roaming\npm\node_modules\electron-builder\index.js:80:42)
    at Object.<anonymous> (C:\Users\****\AppData\Roaming\npm\node_modules\electron-builder\cli.js:36:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

The Node version is __4.2.2__ and npm's __3.5.3__.

Finally, here are the two json configuration files:

`package.json`:
```json
{
  "name": "mark",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "start": "electron main.js"
  },
  "author": "eveningkid",
  "devDependencies": {
    "electron-prebuilt": "^0.36.0"
  }
}
```

and `config.json`:
```json
{
  "win" : {
    "title" : "Mark",
    "version" : "1.0.0",
    "publisher": "eveningkid",
    "icon" : "assets/win/icon.png",
    "verbosity": 1
  }
}
```

Thank you for your time, I hope we'll find out how to make it works!

**Comment by radibit** [comment]
Hey @eveningkid Thanks for the provided information regarding the problem you experienced.

I tried the exact same set up __nodejs 4.2.2__ and __npm 3.5.3__ on __Windows 7__, but I didn't succeed reproducing the same problem.

However looking at the source code for the nodejs __fs__ module and a research I made it seems that the problem might be related to insufficient user rights for the directory where the build script is running or wrong path given for the icon.

Assuming that the second case can be easily verified I can advise you regarding the first one to try execute the build command with an admin rights and share if the problem still appears.

Hope this will give you some clues where the problem might be :-)

**Comment by eveningkid** [comment]
Thank you really much for your answer @radibit!

Sorry, I didn't mention that I had tried executing with admin rights already. Same for the icon path checking! Is there any way we could avoid the icon part of the process? Just to see if it only goes this way because of it.

Also, I'm using Windows 10, but I don't think this should be the cause.

Thank you again for helping me!

**Comment by radibit** [comment]
@eveningkid 

`win.icon` is a required property and it's not possible to run the build without it.

Regarding the __Windows 10__ I also believe this shouldn't be the reason, but still it's an important factor. Unfortunately I don't have machine with this OS version in order to try and confirm.

Another option which might be considered is, if it's possible for you, to see if you're getting the same error on the latest stable versions of nodejs and / or npm. I can recommend the following library for a quick nodejs version management [nvm-windows](https://github.com/coreybutler/nvm-windows) for windows.

**Comment by stefanjudis** [comment]
Hey hey.

I don't see `electron-builder` used in your package.json. can your share the initial command execution.

As it looks like some file permission problem, where do you want to save the installer? Have you tried a different output path?

**Comment by stefanjudis** [comment]
Closed due to inactivity... Feel free to reopen. :)

**Comment by eveningkid** [comment]
Sorry for late reply, and thank you a lot for your answers!

I've been trying out your suggestions and none of them worked for me... 

- @radibit: Working with the latest stable versions of both `node` and `npm` unfortunately didn't change a thing;
- @stefanjudis: indeed, the dependency wasn't in my `package.json` but addind it didn't work. Its latest version is pasted right after this list;
- I am using that execution command: `electron-builder ./app --platform=win --out=dist/win/64 --config=config.json`, and I've tried changing the output path, but same happens.

And so here's the `package.json`:
```json
{
  "name": "mark",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "start": "electron app/main.js"
  },
  "author": "eveningkid",
  "license": "CC0-1.0",
  "devDependencies": {
    "codemirror": "^5.11.0",
    "electron-localshortcut": "^0.6.0",
    "electron-prebuilt": "^0.36.0",
    "highlight.js": "^9.1.0",
    "marked": "^0.3.5",
    "electron-builder": "^2.6.0"
  }
}
```

I really wonder too where the problem might come from... Thank you again for your time, I do appreciate it!

**Comment by mzmousa** [comment]
Any updates on this? Getting this same error.

**Comment by develar** [comment]
@mzmousa electron-builder is completely different now — please open new issue and attach your log.

**Comment by mzmousa** [comment]
Why? It's the exact same issue... Anyways, fixed by changing file permissions, e.g., ```chmod -R 777 appDirectory```
