### ISSUE TITLE
Read values from package.json for several config options

### ISSUE THREAD

**Issue by stefanjudis** [loopline-systems/electron-builder#126]
As dicussed in #123 it would be cool to be able to drop given config options in the config file and rely on things defined inside of the `package.json` e.g. `version`, `name`, etc...

**Comment by chimon2000** [comment]
+1

**Comment by havenchyk** [comment]
@stefanjudis it's already in the electron-complete-builder, if I understand correctly.

**Comment by develar** [comment]
@havenchyk Merging in process. I am preparing docs and other required stuff (e.g. nsis target).

Once docs will be merged, I will revisit issues and close obsolete.
