### ISSUE TITLE
packages on linux don't show icon in desktop entry

### ISSUE THREAD

**Issue by citrusui** [loopline-systems/electron-builder#136]
Haven't seen an issue opened on this yet, so here you go.

**Comment by xseignard** [comment]
Hello @citrusui 

It is a known issue I'm planning to tackle quick.

You're one of the first to try the `.deb` packaging and your feedback and patience is valuable, so thanks!

**Comment by develar** [comment]
Docs: https://developer.gnome.org/integration-guide/stable/desktop-files.html.en

**Comment by develar** [comment]
@xseignard  Will be fixed tomorrow in the electron-complete-builder (and our projects will be merged next week —https://github.com/loopline-systems/electron-builder/issues/138#issuecomment-183715299).

48x48 PNG icon is required, but we will automatically extract it from OS X icns file (if not explicitly provided).
