### ISSUE TITLE
Add option to sign DMG

### ISSUE THREAD

**Issue by Joshua-Smith** [loopline-systems/electron-builder#140]
It's not a huge deal, but I noticed that while electron-packager has an option --sign= to sign Mac .app folders, there is no parallel option in electron-builder to sign the DMG file. It's obviously no big deal to just run codesign on the DMG in my build script, which I did. But for newbie Mac developers, they are going to be confounded why their DMGs are declared "corrupted" by OS X when they try to distribute them. Adding a --sign= option to electron-builder would be a nice touch.

**Comment by develar** [comment]
As far I know DMG should be not signed. It is not required. See http://stackoverflow.com/a/23884014

**Comment by Joshua-Smith** [comment]
That SO answer is dead wrong. Everything changed in Lion.

If you don’t codesign a DMG file, and then you distribute it over the internet, Mac OS X Lion or later will tell you the DMG is “corrupted” as soon as you try to access the app in the file (dragging to Applications or opening directly).

http://stackoverflow.com/questions/9743116/gatekeeper-signing-for-osx-dmgs-outside-of-osx-xcode-mac-app-store

**Comment by develar** [comment]
@Joshua-Smith Strange. Are you sure? My app signed, but DMG not. Try – https://github.com/develar/onshape-desktop-shell/releases I don't think that DMG should be signed, maybe your app is not signed correctly?

Also, my company distributes non-electron app (https://www.jetbrains.com/idea/#chooseYourEdition) and DMG is also not signed. No problem.

**Comment by Joshua-Smith** [comment]
I’m sure I get the error if I don’t sign the DMG, and I don’t get the error if I do sign the DMG.

The DMG you pointed me to doesn’t generate this error, which is interesting. No idea why yours doesn’t need the signature and mine does.

I’m assuming my app is signed correctly because I’m using electron-packager to sign it, and when I check the signature it says it’s okay. I’ll try signing it myself in my build script instead of having packager sign it and see if that makes a difference...

**Comment by rishson** [comment]
I codesign my `.app` but not the `.dmg` and its been working fine for me for over a year.
Can you post the output of `codesign -vvvv` or `spctl`?

**Comment by develar** [comment]
DMG is a disk image file, nothing more. DMG Verification is not related to code signing. It seems, your DMG is corrupted — check it using Disk Utility (Images -> Verify...).

**Comment by develar** [comment]
@Joshua-Smith Please check your security settings: open `System Preferences -> Security & Privacy -> Allow apps downloaded from` Ensure that here `Mac App Store and identified developers` checked.

**Comment by Joshua-Smith** [comment]
$ codesign -vvvv *.app
--prepared:/private/tmp/build/myapp-darwin-x64/myapp.app/Contents/Frameworks/myapp Helper EH.app
--validated:/private/tmp/build/myapp-darwin-x64/myapp.app/Contents/Frameworks/myapp Helper EH.app
--prepared:/private/tmp/build/myapp-darwin-x64/myapp.app/Contents/Frameworks/myapp Helper.app
--validated:/private/tmp/build/myapp-darwin-x64/myapp.app/Contents/Frameworks/myapp Helper.app
--prepared:/private/tmp/build/myapp-darwin-x64/myapp.app/Contents/Frameworks/myapp Helper NP.app
--validated:/private/tmp/build/myapp-darwin-x64/myapp.app/Contents/Frameworks/myapp Helper NP.app
--prepared:/private/tmp/build/myapp-darwin-x64/myapp.app/Contents/Frameworks/Mantle.framework/Versions/Current/.
--validated:/private/tmp/build/myapp-darwin-x64/myapp.app/Contents/Frameworks/Mantle.framework/Versions/Current/.
--prepared:/private/tmp/build/myapp-darwin-x64/myapp.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
--validated:/private/tmp/build/myapp-darwin-x64/myapp.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
--prepared:/private/tmp/build/myapp-darwin-x64/myapp.app/Contents/Frameworks/Squirrel.framework/Versions/Current/.--prepared:/private/tmp/build/myapp-darwin-x64/myapp.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current/.

--validated:/private/tmp/build/myapp-darwin-x64/myapp.app/Contents/Frameworks/Squirrel.framework/Versions/Current/.
--validated:/private/tmp/build/myapp-darwin-x64/myapp.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current/.
myapp.app: valid on disk
myapp.app: satisfies its Designated Requirement

(Note that my app isn’t actually called “myapp.app” but it’s for a client, so I global-replaced the name)

I’m trying again now using codesign in my build script instead of having electron-packager do the signing.

**Comment by Joshua-Smith** [comment]
Confirmed. That’s what it is set to.

**Comment by develar** [comment]
@Joshua-Smith Please check your security settings: open `System Preferences -> Security & Privacy -> Allow apps downloaded from` Ensure that here `Mac App Store and identified developers` checked.

Also, try to open your app directly (from dist folder, as result of `electron-packager` build).

**Comment by Joshua-Smith** [comment]
Aha!

So if I have electron-packager sign my .app, then I need to sign the DMG (which I’m guessing just dives into the DMG and finds the app and re-signs it).

But if I sign it myself, I don’t need to sign the DMG.

So I guess that the real problem is in relying on electron-packager to sign the .app.

-Joshua

**Comment by rishson** [comment]
Just to confirm, your build is something like:
```
create .app
sign
create .dmg
```
in that order?

As long as you dont do anything to the .app contents inbtween signing and running `appdmg` then all should be well.

**Comment by Joshua-Smith** [comment]
Correct. That’s exactly what I do.

When I sign myself by calling codesign, it works right. When I sign by foolishly passing the —sign argument to electron-packager, it doesn’t.

-Joshua

**Comment by develar** [comment]
I don't want to promote here my tool (in any case it will be merged soon), but will be code signed correctly if you will use https://github.com/develar/electron-complete-builder ?

**Comment by rishson** [comment]
I've had codesign fail in the past for either:
1) `--deep` option failed due to xCode issues (so had to sign each app separately)
2) sign then zip then unzip would fail with really long file paths

@develar doesn't `electron-complete-builder` use `electron-packager` underneath though?

@develar the more I look at `electron-complete-builder` the more I really like what you've done :smile:

**Comment by develar** [comment]
> doesn't electron-complete-builder use electron-packager underneath though?

Yes, but not for code signing (although, the command is the same on development machine).

On CI server `electron-complete-builder` pass keychain name explicitly to avoid any issues. 
`electron-complete-builder` build app directly to out dir, without temp dir. 
And there is no question "`As long as you dont do anything to the .app contents inbtween signing and running appdmg then all should be well`" — user just doesn't have a chance to break it :) (because all work is done in the same process in the same time).

**Comment by havenchyk** [comment]
> I don't want to promote here my tool (in any case it will be merged soon)

@develar will it be merged into electron-builder? It's not clear for me.

**Comment by develar** [comment]
@havenchyk Yes. See https://github.com/loopline-systems/electron-builder/issues/138

**Comment by havenchyk** [comment]
@develar it would be nice to add this info to the readme of electron-complete-builder as well.

**Comment by develar** [comment]
@havenchyk Anything can happen. Until PR is not accepted and process is not starting, it is too early. Let's stop off topic here ;)
