### ISSUE TITLE
Overwrite option

### ISSUE THREAD

**Issue by aaaaahaaaaa** [loopline-systems/electron-builder#154]
It would be nice to have an `overwrite` option so that the `"Target already exists"` error is not fired.

**Comment by develar** [comment]
It is already fixed, announce and docs will be soon (several days).

**Comment by aaaaahaaaaa** [comment]
Cool. Thanks.

**Comment by develar** [comment]
You can use [electron-complete-builder](https://github.com/develar/electron-complete-builder) (new API is equal to it) as a quick solution (and to report early feedback ;))
