### ISSUE TITLE
Linux: specifying the arch in config.json is awkward for multi-arch

### ISSUE THREAD

**Issue by adam-lynch** [loopline-systems/electron-builder#159]
Having to specify the arch in the config (or that it's limited to one arch) means if you want to build for both archs, then you need to build for one, edit the json, and build for the other.

**Comment by develar** [comment]
It is already fixed, announce and docs will be soon (several days). You can use [electron-complete-builder](https://github.com/develar/electron-complete-builder) (new API is equal to it) as a quick solution (and to report early feedback ;)) 

Also, please see https://github.com/develar/electron-complete-builder/issues/3#issuecomment-185061083.

**Comment by adam-lynch** [comment]
@develar 

>It is already fixed, announce and docs will be soon (several days)

Several days? Great!! Because I was talking to @stefanjudis about the fact I'm including this in an Electron book and changing the API would be an issue. Is there a branch with the new API and docs?

**Comment by develar** [comment]
@adam-lynch Branch: https://github.com/develar/electron-builder/tree/docs PR: https://github.com/loopline-systems/electron-builder/pull/162

**Comment by adam-lynch** [comment]
Thanks @develar. I'm having trouble installing it from GitHub. It failed on my Windows machine. Failed on my Mac and now even fails on my Mac with `sudo` although it did get further I think (I never usually have to use `sudo`);

```shell
$ sudo npm i -D develar/electron-builder#docs
Password:
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.24","npm":"2.9.0"})
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
 
> fs-xattr@0.1.11 install /Users/adam/Code/GitHub/electron-quick-start/node_modules/electron-builder/node_modules/appdmg/node_modules/fs-xattr
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/adam/.node-gyp/0.10.24"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/Users/adam/Code/GitHub/electron-quick-start/node_modules/electron-builder/node_modules/appdmg/node_modules/fs-xattr/.node-gyp"
  CXX(target) Release/obj.target/xattr/src/error.o
  CXX(target) Release/obj.target/xattr/src/xattr.o
  SOLINK_MODULE(target) Release/xattr.node
  SOLINK_MODULE(target) Release/xattr.node: Finished
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.24","npm":"2.9.0"})
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.24","npm":"2.9.0"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.24","npm":"2.9.0"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.24","npm":"2.9.0"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.24","npm":"2.9.0"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.24","npm":"2.9.0"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.24","npm":"2.9.0"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.24","npm":"2.9.0"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.24","npm":"2.9.0"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.24","npm":"2.9.0"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.24","npm":"2.9.0"})

> macos-alias@0.2.9 install /Users/adam/Code/GitHub/electron-quick-start/node_modules/electron-builder/node_modules/appdmg/node_modules/ds-store/node_modules/macos-alias
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/adam/.node-gyp/0.10.24"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/Users/adam/Code/GitHub/electron-quick-start/node_modules/electron-builder/node_modules/appdmg/node_modules/ds-store/node_modules/macos-alias/.node-gyp"
  CXX(target) Release/obj.target/volume/src/volume.o
  SOLINK_MODULE(target) Release/volume.node
  SOLINK_MODULE(target) Release/volume.node: Finished
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "-D" "develar/electron-builder#docs"
npm ERR! node v0.10.24
npm ERR! npm  v2.9.0
npm ERR! path /Users/adam/Code/GitHub/electron-quick-start/node_modules/electron-builder/out/install-app-deps.js
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, chmod '/Users/adam/Code/GitHub/electron-quick-start/node_modules/electron-builder/out/install-app-deps.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/adam/Code/GitHub/electron-quick-start/npm-debug.log

```

**Comment by adam-lynch** [comment]
Ok sorted it nevermind

**Comment by develar** [comment]
@adam-lynch You cannot install it from github because compilation is required. If you want to use latest API — use [electron-complete-builder](https://www.npmjs.com/package/electron-complete-builder) instead of `electron-builder`. 

[You can still use npm package electron-complete-builder because for now new versions is published often (release cycle is shorter).](https://github.com/develar/electron-complete-builder)

**Comment by adam-lynch** [comment]
@develar I got it working with the branch. I assumed the new API was electron-complete-builder but improved but it doesn't look like it. Thanks.

I hope you don't mind me asking you some questions. I really need to make sure I document this correctly in the book :smile:. I've found a few things which are incorrect *I think*. 

### build/builder property

When using CLI, it looks for a `builder` property in my `package.json`, not `build` like the docs say.

### Does it include electron-packager?

The docs mention that `electron-packager` options can be specified in the `build` property but as far as I can tell from running the new API, it doesn't do generate exectuables at all, just the installer? (I've only ran it for OSX so far by the way). Am I correct in saying then that I need to use `electron-packager`, then the "app path" I give to `electron-builder` would be my `.app` I generated with `electron-packager`?

### Programmatic API

Am I right in saying this is the programmatic API?

```javascript
var builder = require('electron-builder');
builder.init().build({
      platform: 'osx',
    appPath: 'releases/electron-quick-start-darwin-x64/electron-quick-start.app',
    config: {
        osx: {
            "title": "My DMG",
            "icon-size": 80,
            "background": "build/background.png",
            "icon": "build/icon.icns",
            "contents": [
                {
                    "x": 410,
                    "y": 220,
                    "type": "link",
                    "path": "/Applications"
                },
                {
                    "x": 130,
                    "y": 220,
                    "type": "file",
                    "path": "computed path to artifact, do not specify it - will be overwritten"
                }
            ]
        }
    },
    basePath: './'
}, function(err){
  if (err) throw err;
});
```

The `builder` property doesn't seem to be parsed from my `package.json` when using the programmatic API. 

The docs imply that I don't need to give a `background` or `icon` property, that they would be automatically grabbed from my `build` directory, but that's not true... right now the new API will throw an error if they're not given.

Is it weird that I have to give a `basePath` as well as an `appPath`?

### No icon

The resultant DMG does not have my `build/icon.icns` even though the absolute path passed to `appdmg` seems correct.

**Comment by develar** [comment]
> When using CLI, it looks for a builder property in my package.json, not build like the docs say.

Please don't use deprecated CLI. Only `build`. See https://github.com/develar/electron-builder/tree/docs#cli-usage And please use npm scripts — see https://github.com/develar/electron-builder/tree/docs#in-short "Add scripts to the development package.json".

> Am I right in saying this is the programmatic API?

No. It is old deprecated  programmatic API. See https://github.com/develar/electron-builder/tree/docs#programmatic-usage File `node_modules/electron-builder/out/electron-builder.d.ts` is not yet available (because 2.8 is not yet realeased). I have created [gist](https://gist.github.com/develar/1fb32dcb9a62ccf845d4).

> The resultant DMG does not have my build/icon.icns

Please ensure that you follow [simple 4 steps](https://github.com/develar/electron-builder/tree/docs#in-short) and use new, but not old API :)

**Comment by develar** [comment]
> I got it working with the branch

Are you sure? Package doesn't work if you install it from github (because not compiled). Please consider to use `electron-complete-builder` — it is tested and published (0.6.6).

**Comment by adam-lynch** [comment]
Ooooh it's `node_modules/.bin/build`... I gave up after trying just `build` and then went back to using `electron-builder`.

>No. It is old deprecated programmatic API.

I generated the electron-builder.d.ts (although I did get errors) but to be honest I don't find it very clear. I'm never used TypeScript. So I digged into the code and saw the old API. Woops. This gist does look different to what I saw though. So looking at it now, I see https://gist.github.com/develar/1fb32dcb9a62ccf845d4#file-electron-builder-d-ts-L83. That helps, but how can I call it? Is it just this?

```javascript
var builder = require('electron-complete-builder');
builder.build(allConfigInOneObject).then(function(){
  // ...
});
```

>Please ensure that you follow simple 4 steps and use new, but not old API :)

Ok, sorry :smile:. (I assume I don't actually need to use `scripts`)

>Are you sure? Package doesn't work if you install it from github (because not compiled). Please consider to use electron-complete-builder — it is tested and published (0.6.6).

I pulled your branch onto my fork, removed a couple of `bin`s, but in the end still used the old API... woops :)

**Comment by adam-lynch** [comment]
Or... I can't use the programmatic API at all? After installing `electron-complete-builder`, it still has the old API in `index.js`. So it seems I have to use `scripts` and `build`. Ok trying that now :)

**Comment by develar** [comment]
> how can I call it? Is it just this?

Got it. Docs will be improved. You can see https://github.com/loopline-systems/electron-builder/blob/master/src/builder.ts#L31 or in tests (ES6) https://github.com/loopline-systems/electron-builder/blob/master/test/BuildTest.js#L89

> Is it just this?

Not exactly, I hope examples above are clear.

> (I assume I don't actually need to use scripts

No, but in this case you should explicitly pass flags like `dist` or `publish`.

**Comment by develar** [comment]
> it still has the old API in index.js

You can, but you need to require file explicitly — `require('electron-complete-builder/out/packager')` (and then use `Packager` to create new packager).

**Comment by adam-lynch** [comment]
@develar Requiring that explicitly throws this:

```javascript
/Users/adam/Code/GitHub/electron-quick-start/node_modules/electron-complete-builder/out/packager.js:2
const fs = require("fs");
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/adam/Code/GitHub/electron-quick-start/build3.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by develar** [comment]
@adam-lynch What nodejs version do you use?

**Comment by adam-lynch** [comment]
@develar 0.10.24 on the Mac I'm on right now.

**Comment by develar** [comment]
@adam-lynch 0.10.24 is very, very old. NodeJS v4+ is required.

**Comment by adam-lynch** [comment]
@develar Ok I've linked 4.0.0 with nvm. Now I see:

```shell
node build3.js 
/Users/adam/Code/GitHub/electron-quick-start/node_modules/electron-complete-builder/out/packager.js:18
    constructor(options, repositoryInfo = null) {
                                        ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/adam/Code/GitHub/electron-quick-start/build3.js:1:77)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

```

**Comment by adam-lynch** [comment]
Going to try node 5.6.0

**Comment by develar** [comment]
@adam-lynch I am sorry. 0.6.7 published.

**Comment by adam-lynch** [comment]
@develar I've installed 0.6.7 (verified in `electron-complete-builder/package.json`) and I've the same error. (Node 4.0.0 still)

**Comment by develar** [comment]
@adam-lynch I have published fixed 0.6.7 version. (previous version was accidentally not preprocessed by babel).

**Comment by develar** [comment]
@adam-lynch Ok, try 0.6.8. Or run your script with `--harmony_rest_parameters --harmony_default_parameters --harmony_array_includes` (but I think 0.6.8 should help).

**Comment by adam-lynch** [comment]
@develar 0.6.8 fixes that error :+1: thanks

**Comment by adam-lynch** [comment]
Ok I've gotten it packaging the executable by using that, but I guess then if I want an installer, I'll need to require something else and manually pass the executable path onto this other required module. But you've clearly thought this all through, so maybe I should just go with the `scripts` way of doing it for the book. Makes sense.

**Comment by adam-lynch** [comment]
Hmm no, using `scripts` and `build` results in an executable only, no installer.

**Comment by adam-lynch** [comment]
Ok got it with `build --dist --publish`. Sorry now for annoying you @develar :smile:

**Comment by develar** [comment]
> if I want an installer, I'll need to require something else and manually pass the executable path onto this other required module.

No. Just pass `dist: true`.  See [test code](https://github.com/loopline-systems/electron-builder/blob/master/test/BuildTest.js#L84).

>  using scripts and build results in an executable only, no installer.

Script name is important — should be named `dist`. In the [example project](https://github.com/develar/onshape-desktop-shell/blob/master/package.json#L11) no arguments passed to `build`, but result is different. pack: just pack, dist: pack + pack in distributable format, release: `publish` is set set always` (see more https://github.com/develar/electron-builder/blob/builder/docs/deployment.md).

**Comment by adam-lynch** [comment]
> Script name is important

@develar thanks! I coincidentally used `dist`. Good to know though!
