### ISSUE TITLE
Impossible to set ProductName/ProductVersion etc on NSIS windows installer?

### ISSUE THREAD

**Issue by zGrav** [loopline-systems/electron-builder#160]
Hello,

Is there a workaround for this? I can't seem to force it, I tried forking the repo but it errors on npm install...

Using a "modified" version of your template installer (just adding the VIVersionKeys) apparently did nothing as well, http://nsis.sourceforge.net/Reference/VIAddVersionKey , Properties -> Details still shows up blank.

Regards.

**Comment by develar** [comment]
Please use Squirrel.Windows installer — new 2.8 API.
