### ISSUE TITLE
npmignore collision with cli.js

### ISSUE THREAD

**Issue by avoidwork** [loopline-systems/electron-builder#168]
Pull request #162 introduced a new CLI dependency on `./docs` which is ignored by `.npmignore`.

**Comment by michaelbrooks** [comment]
I believe I am probably encountering this issue as well, on my OSX build:

```bash
> electron-builder --out="dist/osx" --platform=osx --config=electron-builder-config.json "release/MyApp.app"

fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/jenkins/workspace/MyApp/node_modules/electron-builder/docs/deprecated-usage.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.<anonymous> (/Users/jenkins/workspace/MyApp/node_modules/electron-builder/cli.js:17:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

**Comment by avoidwork** [comment]
Now we wait...

**Comment by avoidwork** [comment]
@develar please merge ASAP

**Comment by stefanjudis** [comment]
I'm on it. :)

**Comment by develar** [comment]
@stefanjudis To auto push new npm version, commit message should be be according to semantic-release. To trigger publish, I pushed "fix: remove unused dependency lodash.camelcase" Version will be published after test pass.

**Comment by stefanjudis** [comment]
okay. I'm waiting then. :)

**Comment by stefanjudis** [comment]
@develar And it's failing.

**Comment by develar** [comment]
@stefanjudis I see that it is not yet finished — https://travis-ci.org/loopline-systems/electron-builder/builds/111282493 (OS X travis agent doesn't support caches, so, it is slower than linux).

**Comment by stefanjudis** [comment]
>  To trigger publish, I pushed "fix: remove unused dependency lodash.camelcase" Version will be published after test pass.

You pushed directly to master... okay. @develar this definitely has to be documented. :)

**Comment by IntegerMan** [comment]
This issue is happening for me with latest any time I try to invoke electron-builder from the command line on a Windows machine.

**Comment by develar** [comment]
@IntegerMan Please file new issue and attach error stack trace.
