### ISSUE TITLE
Collaboration plan

### ISSUE THREAD

**Issue by stefanjudis** [loopline-systems/electron-builder#170]
@develar @avoidwork @havenchyk @citrusui 

Heyooo people.

So we had the first break which is something that we should avoid in the future. :)
Let's discuss here how we want to proceed in the future. Goal should be to provide a nice and stable project. :)

That for let's define a review process, a release process and how we want to proceed with the whole thing. It's a migration phase atm which might make it a bit jumpy, but I think we can come through it without any more struggles. 

We have 2 additional people who are willing to contribute ( @develar and @avoidwork ). I'm more than happy to invite more people if anyone is up for it. 

Currently I've got pretty much life happening, so I'm not sure how big my impact can be in near future. But I'll jump in completely when things are sorted out.

So how do we want to proceed. It's open source and collaboration should be the goal - as it leads to a better project. What do all think? :blush: 

---------------------------------------

First of all, as I wasn't involved that much, the auto publish should be documented somewhere. :)

**Comment by develar** [comment]
> the auto publish should be documented somewhere

PR to update `CONTRIBUTING.md` will be prepared tomorrow morning (CET).

> how we want to proceed in the future

Tests should use `electron-builder` as a published package to avoid such errors. Not from sources. I will do it. Reviews (#162) doesn't help to prevent such errors :(

**Comment by stefanjudis** [comment]
> Reviews (#162) doesn't help to prevent such errors 

Still would love to keep reviews going.

What I'm missing too, is an introduction to the new development flow as I'm not familiar with TypeScript.

**Comment by havenchyk** [comment]
I'm also thinking that review is not really helpful. We have free time to do open source from time to time, but not always, so tests are much better, IMO. We can try to increase test coverage and create tests for every new feature. @develar used `ava`, if I'm not wrong.

@stefanjudis let's learn new language, it's a superset of javascript, it's newer too late to learn something new :smile:

**Comment by stefanjudis** [comment]
Sure thing, that proper test coverage should continue going on. :) 

> let's learn new language, it's a superset of javascript, it's newer too late to learn something new

I'm not against learning this. I'm just saying that a nice introduction would help me and new people that want to jump in too...

**Comment by develar** [comment]
> review is not really helpful

> Still would love to keep reviews going.

Definitely, reviews must be. Not discussable. Commit as a PR in a separate branch. I violated this rule [here](https://github.com/loopline-systems/electron-builder/issues/168#issuecomment-187836257) only to trigger publish (result of missed docs, my fault).

> What I'm missing too, is an introduction to the new development flow

Do you use IDE (WebStorm, IDEA?) or plain text editor? Don't agitate — just to prioritise.  
There is a possibility to use TS as JS — without recompilation, just run — i.e. your development flow will be not broken. It is not required for WebStorm/(other smart IDE), so it is not yet done.

**Comment by avoidwork** [comment]
Hi,

I'm late to the conversation, 'cause it's still my work day. Reviews do help block errors like #162 introduced, if the participants do not rush. Unless you can run the entire workflow in a private environment, you really don't know what's happening if you automatically publish; such actions are dangerous when you consider the cost of introducing an error downstream (it's a hidden cost obviously, you don't pay in time, stress or $).

**Comment by havenchyk** [comment]
I also don't like the idea to publish npm version automatically. 

@avoidwork I reviews the patch and didn't found any issue, sometimes it's hard to see without the verifying(check on local machine).

**Comment by develar** [comment]
`semantic-release` documented — #178.

**Comment by havenchyk** [comment]
Can be closed, I guess. /cc @stefanjudis @develar

**Comment by stefanjudis** [comment]
Yeha let's do it...

Project is good rollin. :)

**Comment by develar** [comment]
Note for contributors: You will get error `npm ERR! cb() never called!` if you will use NodeJS 5.9 (released two days ago). CI broken as well (only nodejs 4 successful). Workaround — use nodejs 5.8. I have fixed CI to explicitly use nodejs 5.8.
