### ISSUE TITLE
Unable to build windows app in osx

### ISSUE THREAD

**Issue by incurito** [loopline-systems/electron-builder#179]
The build scripts by default only create DMG version of my app when run in an osx environment. Adding `win` section to `package.json` doesn't seem to help. Am I missing something?

**Comment by develar** [comment]
Please [be aware of caveats](https://github.com/loopline-systems/electron-builder/blob/master/docs/multi-platform-build.md).

`platform` by default equals to current platform. OS X in your case.  Please specify `--patform darwin win32`

**Comment by incurito** [comment]
Thnx for the quick response.

**Comment by develar** [comment]
New API is not yet stabilised and we are open to feedback. Our goal is to avoid boilerplate configuration — suggest workflows, but not tons of options.

If you want to build windows on OS X to produce production ready artifacts — we strongly recommend to use CI. Only CI. Nothing to improve.

If you want to build windows on OS X to produce artifact to test (e.g. build on OS X and test using Parallels Desktop) — may be we can add support for magic script name `build-win`.
