### ISSUE TITLE
npm run build:macos ouputs nothing

### ISSUE THREAD

**Issue by s-a** [loopline-systems/electron-builder#18]
```npm run build:macos``` produces no output. Is this command possible on windows?

```
C:\git\fileSharp>npm run build:macos

> fileSharp@0.1.0 build:macos C:\git\fileSharp
> npm run clean:macos && electron-packager ./app "fileSharp" --out=dist/macos --platform=darwin --arch=x64 --version=0.25.3 --icon=assets/macos/icon.icns


> fileSharp@0.1.0 clean:macos C:\git\fileSharp
> rm -rf ./dist/macos

Packaging app for platform darwin x64 using electron v0.25.3
```

**Comment by stefanjudis** [comment]
Uhm, this is an issue on https://github.com/maxogden/electron-packager or?

**Comment by s-a** [comment]
So far electron system is new for me. This case would be ```pack:macos``` command I think?

**Comment by stefanjudis** [comment]
Ja, but you're stuck with `build:macos` which is using `electron-packager`. Assuming you posted the complete output.

electron-packager -> create packed applications
electron-builder -> create installer for these packed applications.

**Comment by s-a** [comment]
Yes! I was confused ^^ :+1: thanks.

**Comment by stefanjudis** [comment]
No problem. :bowtie:
