### ISSUE TITLE
Problems downloading electron

### ISSUE THREAD

**Issue by thanpolas** [loopline-systems/electron-builder#180]
Hello, just installed 2.8.3 and trying to create a build...

When i run `npm run pack` I get this error:
```
[19:08:54] $ npm run pack

> Reveal@6.0.0-alpha.1 pack /Users/thanpolas/Projects/work/insightReplay/reveal-electron
> build

Skipping app dependencies installation because dev and app dependencies are not separated
Downloading electron-v.36.7-darwin-x64.zip
Error: GET https://github.com/atom/electron/releases/download/v.36.7/electron-v.36.7-darwin-x64.zip returned 404
Error: Compound error:

Error #1 --------------------------------------------------------------------------------
undefined

Error #2 --------------------------------------------------------------------------------
TypeError: A value null was yielded that could not be treated as a promise

    See http://goo.gl/MqrFmX

From coroutine:
    at Function.Promise.coroutine (/Users/thanpolas/Projects/work/insightReplay/reveal-electron/node_modules/electron-builder/node_modules/bluebird/js/release/generators.js:175:17)
    at tsAwaiter (/Users/thanpolas/Projects/work/insightReplay/reveal-electron/node_modules/electron-builder/src/awaiter.ts:4:35)
```

As you can notice it tries to download:

> https://github.com/atom/electron/releases/download/v.36.7/electron-v.36.7-darwin-x64.zip

when it should be downloading:

> https://github.com/atom/electron/releases/download/v0.36.7/electron-v0.36.7-darwin-x64.zip

Another issue I have is with the `"postinstall": "install-app-deps",` script... it fails after npm install, when i run it directly from `node_modules/.bin/install-app-deps` i get:

```
Installing app dependencies for arch x64 to /Users/thanpolas/Projects/work/insightReplay/reveal-electron/app
Error: spawn npm ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
```

I use nvm

**Comment by develar** [comment]
Please specify `"electron-prebuilt": "^0.36.7"` in the development package.json. I suppose, it is specified as `0.36.7` now. Please change it to `^0.36.7`

**Comment by develar** [comment]
> Another issue I have is with the "postinstall": "install-app-dept"

You don't need this because you don't use [two-package.json project layout](https://github.com/loopline-systems/electron-builder/issues/39#issuecomment-188855084). Remove `postinstall` from your package.json (or consider to use suggested layout).

**Comment by thanpolas** [comment]
> Please specify "electron-prebuilt": "^0.36.7" in the development package.json. I suppose, it is specified as 0.36.7 now. Please change it to ^0.36.7

Yes, that solved my problem (!).

> You don't need this because you don't use two-package.json project layout. Remove postinstall from your package.json (or consider to use suggested layout).

Ok removed, as a newcomer i'm having a hard time wrapping my head around the flow, readme doesn't help...

I need to run the builder on a stripped down version of the current app, how would i go about doint that?

Thank you for the fast response @develar!

**Comment by develar** [comment]
> I need to run the builder on a stripped down version of the current app, how would i go about doint that?

Don't quite understand. Do you mean that packaged app (.app osx or .exe win) processed by 3rd party tool and you want to build only installer?

**Comment by develar** [comment]
> Yes, that solved my problem (!).

It is a bug, will be  fixed.

**Comment by thanpolas** [comment]
> Don't quite understand. Do you mean that packaged app (.app osx or .exe win) processed by 3rd party tool and you want to build only installer?

I need to remove all dev deps from node_modules using `npm prune --development` on a copy of the app... and cleanup test folders and the like...  Is there a way to use the output of electron-packager to just generate the installers (.dmg) based on that bundle vs running the packager in the builder?

There are a few packager options that I cannot understand how to pass to the builder like `prune` and `asar`

**Comment by thanpolas** [comment]
> There are a few packager options that I cannot understand how to pass to the builder like prune and asar

ok figured this out, missed the line where the "build" key in package.json is used for that purpose.

**Comment by develar** [comment]
@thanpolas 

> asar

asar is used by default. JFYI: See [step 1](https://github.com/loopline-systems/electron-builder#in-short) `This object will be used as a source of electron-packager options. You can specify any other options here.`

> I need to remove all dev deps from node_modules using npm prune --development on a copy of the app... 

Don't try to solve inexistent issue. Don't waste your time. See [two-package.json project layout](https://github.com/loopline-systems/electron-builder/issues/39#issuecomment-188855084).

**Comment by havenchyk** [comment]
@thanpolas @develar electron-packager supports `ignore` option, where you can provide a regex to match the packages you wouldn't like to add to the asar. But I like the idea of two-package.json layout, it makes sense.

**Comment by develar** [comment]
@havenchyk It is exactly what I mean — "it will be constant battle". It is nightmare. Just use two-package.son layout and forget about it.
