### ISSUE TITLE
Log some info during the building

### ISSUE THREAD

**Issue by havenchyk** [loopline-systems/electron-builder#181]
Current build process takes a few minutes in my case even on i7 with ssd, so it would be better to log some information during this build process, at least "start script", "start packaging" etc.

Does it make sense? /cc @develar @stefanjudis

**Comment by develar** [comment]
Please specify your OS and target OS.

I thought about it. And decided, that detailed log is not needed.

Please keep in mind: Windows IO is slow compare to nix (Linux, OS X).

```
develar-imac:onshape-desktop-shell develar$ time npm run dist

> @ dist /Users/develar/Documents/onshape-desktop-shell
> npm run compile && build


> @ compile /Users/develar/Documents/onshape-desktop-shell
> rimraf app/out && tsconfig -i 2 && tsc

Installing app dependencies for arch x64 to /Users/develar/Documents/onshape-desktop-shell/app

> nslog@3.0.0 install /Users/develar/Documents/onshape-desktop-shell/app/node_modules/nslog
> node-gyp rebuild

  CXX(target) Release/obj.target/nslog/src/main.o
  CXX(target) Release/obj.target/nslog/src/nslog_mac.o
  SOLINK_MODULE(target) Release/nslog.node
Onshape@0.4.1 /Users/develar/Documents/onshape-desktop-shell/app
└── nslog@3.0.0 

Packaging app for platform darwin x64 using electron v0.36.8
Signing app
Creating DMG
Creating ZIP for Squirrel.Mac

real	0m29.767s
user	0m22.705s
sys	0m1.236s
```

Who consumes a lot of time?
* Linux: we use `xz` by default. Compression takes a lot of time. Even if CPU 4 GHz Intel Core i7.
* OS X: zip (squirrel.mac) and dmg — the same reason. Compression. And it will be even worse soon — https://github.com/LinusU/node-appdmg/pull/86.
* Windows: squirrel.windows.  the same reason * number of artifacts (full-, delta-, installer). Compression.

What we can do? We already do — `xz`, `codesign`, etc cannot utilise modern CPU. It is shame, but fact — miserable 100%. Not 500% (as IntelliJ IDEA does, for example). So, we run all tasks in parallel.

So — it is not easy to display progress for parallel tasks (performed by native processes). Is it worth it? Do you want to see yet another confirmation that `xz` or `bzip2` take a lot of time?  Don't think so. Setup CI and forget.

**Comment by havenchyk** [comment]
OS: os x el capitan
Targer: os x

I have tried with your unshape-desktop-shell. It's ok for now, but in the future it will be a great enhancement.

**Comment by develar** [comment]
@havenchyk Please provide exact timing — use `time` command.

**Comment by develar** [comment]
Yes, I experimented to add progress to `zip` native command. It can print dots every n packed MB. Well, decided that it is ok to not print :) No way to speed up in any case :(

**Comment by havenchyk** [comment]
I'm closing it for now, not a high priority. Maybe we can open it later.
