### ISSUE TITLE
Configure build resources directory

### ISSUE THREAD

**Issue by develar** [loopline-systems/electron-builder#184]
Proposal: 

Use [directories](https://docs.npmjs.com/files/package.json#directories).`buildResources` key in the development package.json.

Default value: `build`
Path relative to the root of project (i.e. development package.json).

**Comment by uggrock** [comment]
This will be great!

**Comment by develar** [comment]
@uggrock Could you please specify your desired value (name of your `build` folder)? May be we can just try to use it by default (i.e. if it is named `assets`, it is reasonable to just try to find such folder in the project dir automatically by default).

**Comment by demetris-manikas** [comment]
Why not just follow the path given? e.g: "background": "RELATIVE_DIR/MY_BACKGROUND_NAME.jpg" ?

**Comment by develar** [comment]
@demetris-manikas 

As user, I don't want to specify all of required paths.
As user, I want to build my app in distributable format. Don't learn all required tools to do it.

`electron-builder` does it for you. You need just follow convention.

So, I think, it is better for user just follow some convention. And tool will do of the rest.

**Comment by demetris-manikas** [comment]
@develar I am not saying that defaults should not exist. But that a good tool allows the user to override defaults. For me it's not a good thing for a tool to enforce the layout of an application in anyway.
e.g. Say that an app uses the same icon that is being used for the installer. The tool enforces the user to duplicate the resource leading to another thing to remember to do when changing the icon.

**Comment by develar** [comment]
@demetris-manikas Understand. It will be implemented. Not recommended, but `not a good thing for a tool to enforce the layout of an application`.

**Comment by develar** [comment]
@demetris-manikas I have realised that you request is already implemented – see https://github.com/loopline-systems/electron-builder#distributable-format-configuration (just specify own `background`). If it doesn't work, please file an issue.

**Comment by demetris-manikas** [comment]
It was not my request but anyway I 'll try it first thing in the morning...

**Comment by jayalfredprufrock** [comment]
I've been trying to specify my own location for the OSX icon file as detailed in the docs and it doesn't seem to be working. I know it's finding the icon because if I alter the path to something bogus it throws an error. Specifying the background image DOES work though. Oddly enough, when I place the icon.icns file and background.png file in the "build" directory and rely on the defaults, the icon loads properly but not the background. I've had to use a combination of both methods to get everything to work.

**Comment by develar** [comment]
@jayalfredprufrock Reported as #197.
