### ISSUE TITLE
Add Electron Release Server as an alternative to Nuts

### ISSUE THREAD

**Issue by ArekSredzki** [loopline-systems/electron-builder#185]
Initially I tried using nuts, but seeing as my use case of releasing an application internally at Tesla did not deal with Github, I ended up developing the app from scratch. Perhaps it'd be of use to others as well, it'd be great if you could link to it as I have to this :) https://github.com/ArekSredzki/electron-release-server

**Comment by develar** [comment]
Offtopic: Is https://github.com/GitbookIO/nuts/issues/32 fixed in your package?

**Comment by ArekSredzki** [comment]
Yup!

**Comment by ArekSredzki** [comment]
@develar Hey, just wondering if you've gotten a chance to take a look and what you think :)

Thanks!
