### ISSUE TITLE
How to define custom nsisconf.nsh?

### ISSUE THREAD

**Issue by s-a** [loopline-systems/electron-builder#19]
As far I can see nsis takes by default ```nsisconf.nsh``` within its program folder (on windows). Is it possible to point to a custom ```nsisconf.nsh``` from packager.json? I need this to define symbols for installer like version company and so on.

**Comment by stefanjudis** [comment]
Jup. Sure.

We can tackle this in the future. :)

If you wanna PR, this would be more than welcome. :)

**Comment by stefanjudis** [comment]
It's no included in options. :)
