### ISSUE TITLE
Releases file for Windows not uploaded to Github

### ISSUE THREAD

**Issue by mcaoun** [loopline-systems/electron-builder#190]
I think the RELEASES file is needed on the nuts server and for windows updates, but it doesn't seem to get uploaded to Github.
(See https://github.com/GitbookIO/nuts/blob/master/docs/update-windows.md)

Looking at the code it seems to be the intended behavior given that disaptchArtifactCreated is called only for the Setup.exe and the nuget package.
https://github.com/loopline-systems/electron-builder/blob/master/src/winPackager.ts#L138

Why is that? Shouldn't the Releases file be included as well.

**Comment by develar** [comment]
> Why is that?

Not implemented due to https://github.com/GitbookIO/nuts/issues/32.

**Comment by mcaoun** [comment]
Should I disable 32 bits releases - would that help?
Do I need then to manually upload the Releases files?
In general do you have any workaround or pending fix?

**Comment by develar** [comment]
I will try to fix it today.

**Comment by mcaoun** [comment]
ok, thanks!

**Comment by mcaoun** [comment]
Is there something I can do to help here?

What is the plan for the fix?
 - Upload the RELEASES file when a single architecture is supported,
 - Or upload both releases files and fix https://github.com/GitbookIO/nuts/issues/32,
 - Or use something other than the nuts server?

Thanks

**Comment by develar** [comment]
Fixed. v2.8.5 will be published in several hours.

We upload RELEASES for x64 and RELEASES-ia32 for ia-32. Nuts issue should be fixed anyway to use ia32. Currently, you can use x64.

Please note — you should specify [remoteReleases](https://github.com/electronjs/windows-installer#usage) to " If given, these will be downloaded to create delta updates". I haven't tried it yet, so, cannot five details instruction.

**Comment by develar** [comment]
@mcaoun Does `RELEASES-ia32` solution works for you? Or I can revert this fix because of https://github.com/electron-userland/electron-builder/issues/359#issuecomment-218746118 ?

**Comment by mcaoun** [comment]
I have been building for 64-bit only since the lack of support on nuts server did not help me move further with the support for both releases versions and 32-bit is not very common for our users.
