### ISSUE TITLE
Small typo in example

### ISSUE THREAD

**Issue by BenjaminDobler** [loopline-systems/electron-builder#2]
Hey,

first thanks for this awesome project!
There is a small confusion in the example package.json
It refers to assets/macos/loopline.icns but the directory structure says mount.icns

Thanks again!

**Comment by stefanjudis** [comment]
Thanks. We'll fix that, right now. :)

Glad you like it and I hope it's running smoothly. :)

**Comment by stefanjudis** [comment]
@BenjaminDobler 

Actually the directory structure shows both icon sets.

```
directory structure

desktop
  |-- app                               // actual electron application
  |
  |-- assets                            // build related assets
    |-- macos                           // build assets for macos
      |-- installer.png                 //   -> referenced in packager.json
      |-- mount.icns
      |-- loopline.icns
```

And then the command for the electron packager refers to `loopline.icns` which is correct.

`"build:macos": "npm run clean:macos && electron-packager ./app \"Loopline Systems\" --out=dist/macos --platform=darwin --arch=x64 --version=0.25.3 --icon=assets/macos/loopline.icns"`

The mount icon is currently referenced in `packager.json`

```
  "macos" : {
    "title": "Loopline Systems",
    "background": "assets/macos/installer.png",
    "icon": "assets/macos/mount.icns",
```

Which also correct. I'll update the readme to make the different icons more clear and close it.

Thanks for pointing out confusing and feel free to reopen. :)
