### ISSUE TITLE
Problem building the windows installer

### ISSUE THREAD

**Issue by ahgan84** [loopline-systems/electron-builder#217]
Hi guys, I'm trying to build a window installer for my application using electron-builder, below is my package.json file:

`{
  "name": "electron-packager-keypad",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "electron .",
    "pack": "electron-packager . keypad --platform=win32 --arch=ia32 --version=0.35.4 --icon=my.ico --overwrite=1",
    "build": "electron-builder \"keypad-win32-ia32\" --platform=win --out=\"dist/win\" --config=builder.json"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "electron-packager": "^5.1.1",
    "electron-prebuilt": "^0.34.3",
    "nconf": "^0.8.2",
    "rcedit": "^0.3.0",
    "rimraf": "^2.5.2"
  }
}`

Below is my builder.json file:

`{
  "win" : {
    "title" : "myqio-keypad",
    "icon" : "myQ.ico"
  }
}
`

When I type "npm run build" the below error occured:

C:\electron-packager-keypad\node_modules\electron-builder\cli.js:57
builder.build( Object.assign( cli.flags, {
                      ^
TypeError: undefined is not a function
    at Object.<anonymous> (C:\Work\Project 2015\electron-packager-myq-io-keypad\node_modules\electron-builder\cli.js:57:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Do you guys know what went wrong?

**Comment by develar** [comment]
What node version are you on? NodeJS 4+ is required.

**Comment by ahgan84** [comment]
I have updated my NodeJS to version 4+ and I try build again.
Now I have another error:

Error: makensis failed
    at ChildProcess.<anonymous> (C:\Work\Project 2015\electron-packager-myq-io-keypad\node_modules\electron-builder\lib\win.js:97:26)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:134:18)
    at node.js:962:3

Do you guys know why?

**Comment by develar** [comment]
Could you please provide full log?

**Comment by ahgan84** [comment]
I have successfully created the windows installer.
The problem just now is I need to install the NSIS: Nullsoft Scriptable Install System first.

**Comment by develar** [comment]
Please consider to use new API. And use Squirrel.Windows (default if you use new API) instead of NSIS.

**Comment by ahgan84** [comment]
Don't get what u mean.
U mean I can install Squirrel.Windows and the makensis failed problem can be solved too?

**Comment by develar** [comment]
I mean that since version 2.8 electron-builder has a new API and I recommend to use it. NSIS is also deprecated.

**Comment by ahgan84** [comment]
U mean I have to uninstall the NSIS and install the Squirrel.Windows and then rebuild the installer again?
Any step by step instruction to follow if I use Squirrel.Windows?

**Comment by develar** [comment]
Please see readme [In short](https://github.com/loopline-systems/electron-builder#in-short).

**Comment by ahgan84** [comment]
Yes. This is what I follow to build my windows installer just now.
But I can't find any Squirrel.Windows info in your link.

**Comment by develar** [comment]
Your `package.json` shows that you use old API. You don't need electron-packager and your script tasks should be exactly like in the docs (step 3 Add scripts).

(also, please don't forget about https://github.com/electronjs/windows-installer#handling-squirrel-events).
