### ISSUE TITLE
Windows installer dist files confusion

### ISSUE THREAD

**Issue by demetris-manikas** [loopline-systems/electron-builder#223]
Using 2.8.6 when i run npm run dist on windows I get the following file structure under the dist directory and it makes me wonder...

under the win directory there are to identical RELEASE files one named RELEASE-ia32 which both reference a AppName-version-full.nupkg file

on the other hand in win-x64 directory there is a RELEASES file that references a  AppName-version-full.nupkg which doesn't exist and that is because the nupkg filename contains the arch AppName-version-arch-full.nupkg

Is there something wrong here or there is something that I am missing?
I would be glad to help out if needed.

Thanks

**Comment by develar** [comment]
> one named RELEASE-ia32

Please see #190 

> references a AppName-version-full.nupkg which doesn't exist 

I will check, thanks.
