### ISSUE TITLE
Expose NoMsi option

### ISSUE THREAD

**Issue by andrewwebber** [loopline-systems/electron-builder#250]
Currently building on windows always tries to build the WIX MSI project. 
Currently I am only distributing the application without the MSI and the build time is very long building the MSI

**Comment by demetris-manikas** [comment]
It is already exposed. Add "noMsi" = true to the win section of your config

**Comment by andrewwebber** [comment]
I do not see where the noMsi flag is being propagated via the options.
[https://github.com/loopline-systems/electron-builder/blob/master/src/winPackager.ts#L113](https://github.com/loopline-systems/electron-builder/blob/master/src/winPackager.ts#L113)

**Comment by demetris-manikas** [comment]
I would READ the docs first and follow the instructions (Distributable Format Configuration https://github.com/electronjs/windows-installer#usage) before start digging into code that I don't understand.
https://github.com/loopline-systems/electron-builder/blob/master/src/winPackager.ts#L113

The option is passed in through the customBuildOptions so set the option and see what it does for you.

**Comment by develar** [comment]
Related: https://github.com/electronjs/windows-installer/issues/40

**Comment by andrewwebber** [comment]
The following json does not work for me

```json
"build": {
    "app-bundle-id": "com.brainloop.dox.administration",
    "app-category-type": "com.brainloop.dox.administration",
    "iconUrl": "http://icons.iconarchive.com/icons/custom-icon-design/flatastic-11/128/Customer-service-icon.ico",
    "setupIcon": "build/icon.ico",
    "icon": "build/icon.ico",
    "overwrite": true,
    "authors": "brainloop",
    "owners": "brainloop",
    "noMsi": true,
    "win":{
      "CompanyName" : "brainloop",
      "title" : "DOX Administration",
      "icon": "build/icon.ico",
      "noMsi": true
    }
  }
```

**Comment by develar** [comment]
@andrewwebber Sorry for confusing (#251), but do you use two-package.json structure or not? If yes, please ensure that `build.win.noMsi` in the development package.json (not in app).

**Comment by andrewwebber** [comment]
I have been living happily with two package.json files, one in the root folder and one nested.
I started with way as I wanted to exclude node_modules from the package builder. 

Root Folder
```json
"scripts": {
    "build": "webpack --progress --colors --bail",
    "dev": "webpack --watch --progress --colors --display-modules --display-chunks --devtool inline-source-map --bail",
    "deploy": "webpack -p --progress --colors --bail",
    "start": "electron www/main.js",
    "postinstall": "install-app-deps",
    "pack": "build --appDir www/",
    "dist": "build --appDir www/"
  },
```

WWW folder
```json
{
  "name": "administration",
  "productName": "DOX Administration",
  "main": "main.js",
  "description": "DOX Administration",
  "author": {
    "name": "brainloop"
  },
  "owner": "brainloop",
  "version":"1.0.0",
  "build": {
    "app-bundle-id": "com.brainloop.dox.administration",
    "app-category-type": "com.brainloop.dox.administration",
    "iconUrl": "http://icons.iconarchive.com/icons/custom-icon-design/flatastic-11/128/Customer-service-icon.ico",
    "setupIcon": "build/icon.ico",
    "icon": "build/icon.ico",
    "overwrite": true,
    "authors": "brainloop",
    "owners": "brainloop",
    "noMsi": true,
    "win":{
      "CompanyName" : "brainloop",
      "title" : "DOX Administration",
      "icon": "build/icon.ico",
      "noMsi": true
    }
  }
}
```

**Comment by develar** [comment]
So, please, for now, duplicate `build` in the development package.json (in the root folder), as it stated in the docs. 

And your opinion about #251 is important for us.

**Comment by demetris-manikas** [comment]
Well.. here is how I use it. 
in ROOT package.json
```
 "build": {
    "osx": {
      "background": "",
      "icon": "",
      "icon-size": 80,
      "contents": [
        { "x": 438, "y": 144, "type": "link", "path": "/Applications" },
        { "x": 192, "y": 144, "type": "file" }
      ]
    },
    "win": {
      "iconUrl":"",
      "setupIcon":"",
      "loadingGif": "",
      "noMsi": "true"
    }
  }

```
in WWW package.json

```
  "build": {
    "app-bundle-id": "your.id",
    "app-category-type": "your.app.category.type"
  }
```

Hope it helps

**Comment by demetris-manikas** [comment]
I would expect not to need to the www package.json entry but it wont go further without it AFAIK. 
@develar Maybe you can give some insight into this

**Comment by andrewwebber** [comment]
thanks i will give it a try.

i personally find having a the icon information in the www package.json file as this is relative folder i wish to package. I use webpack (reactjs,babel,etc.) as a development flow before packaging and like to have a destination folder that i could then say i wish to package. this means i dont have to define flags for folders that have to be excluded (it is implict that everything in the www folder is to be packaged)

**Comment by demetris-manikas** [comment]
the iconUrl can be kept in the www/package.json

**Comment by andrewwebber** [comment]
but according to @demetris-manikas  the "noMsi" cannot. is this not inconsistent?

**Comment by develar** [comment]
>  is this not inconsistent?

Yes, it is inconsistent and confusing. See #251
