### ISSUE TITLE
Remove support of `build` in the application package.json

### ISSUE THREAD

**Issue by develar** [loopline-systems/electron-builder#251]
It is a source of confusion.

Why `iconUrl`, all electron-packager options should be specified in app package.json, but electron-builder specific options (`extraResources`) and windows-installer/appdmg options in the dev?

My proposal: use only `build` in the dev package.json. Also, it is important, because app paths should be relative to project dir (and in case of dev package.json it is clear and expected).

We can do this breaking change as part of 3.0 release (and remove deprecated <2.8 API).

**Comment by havenchyk** [comment]
I'm agree, let's use the only place to make all the configurations.
