### ISSUE TITLE
Weird "green" dialogin windows 7 64

### ISSUE THREAD

**Issue by marcopiraccini** [loopline-systems/electron-builder#253]
Hi, 
I created an installer for win64 and I run it in Windows 7. 
When I run it, a strange "green" dialog appears (see attachments). Probably it should be a dialog saying that the installer it's doing the install (copying the files, etc). But it's weird :)
Did anyone had the same behaviour?

![squirrel](https://cloud.githubusercontent.com/assets/668050/13856837/6e3dae3c-ec77-11e5-8c81-c5bdc6655ebe.png)

**Comment by develar** [comment]
As far I understand, it is ok, please ask about it in the [windows-installer](https://github.com/electronjs/windows-installer/issues).
