### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by hhammoud01** [loopline-systems/electron-builder#29]
Guys how do I build on windows ? 
I installed NSIS but it is still giving me an error that makensis is not recognized and NSIS is not found.
Please help :(

**Comment by stefanjudis** [comment]
Console output might help. ;)

**Comment by hhammoud01** [comment]
- Starting build for ´win´ - 
- makensis not found.
  Please install "nullsoft scriptable install system"
  http://nsis.sourceforge.net/Download
... (error stack: ... )

The problem is that I already installed nsis but I keep getting this error :'(

**Comment by stefanjudis** [comment]
Can you please paste the complete output of the terminal and your config files( `package.json`, `packager.json`)?

**Comment by hhammoud01** [comment]
- Starting build for 'win' -
- makensis not found.
Please install "nullsoft scriptable install system"
http://nsis.sourcefourge.net/Download

C:\Users\Hussein\AppData\Roaming\npm\node_modules\electron-builder\cli.js:30
   throw error;
	 
Error: makensis failed
	at ChildProcess.<anonymous> (C:\Users\Hussein\AppData\Roaming\npm\node_modules\electron-builder\lib\win.js:72:26)
	at ChildProcess.emit (events.js: 107:17)
	at Process.ChildProcess._handle.onexit (child_process.js: 1072:12)
	at child_process.js:1144:20
	at process._tickCallback (node.js:355:11)
	at Function.Module.runMain (module.js:503:11)
	at node.js:814:3


Config Files: 
package.json
{
  "name"    : "myapp",
  "productName": "MyApp",
  "version" : "0.1.0",
  "main"    : "main.js"
}

Thank you for your help,

**Comment by stefanjudis** [comment]
I'm not sure if I can help there.

I assume, when typing `makensis` in your console, you get a `command not found` or something similar?

**Comment by hhammoud01** [comment]
yes, i get exactly "makensis is not recognized as an internal or external command, operable program or batch file"

**Comment by stefanjudis** [comment]
Well... I'm not a windows person. 

Sorry. :(

It has to be present in your environment. Before fixing that it simply can't work.

But if you found the problem, it would be great when you could check the docs here and maybe add some improvements? 

Sorry, again that I can't help.

**Comment by hhammoud01** [comment]
neither am I but I need this to my work :( 
I added this to my environment variables and it still did not work :/
Thanks for your help anyways.

**Comment by null9beta** [comment]
hi @hhammoud01

have you tried opening a new terminal after you added the env variable.
afaik the global vars are only assigned once you open a terminal, same as for unix based shells/terminals

maybe that helps.

**Comment by hhammoud01** [comment]
yes I did that :(

**Comment by null9beta** [comment]
Have you tried just adding the path in your current session?
```
echo %PATH%;
set PATH=%PATH%;C:\...
echo %PATH%;
```

**Comment by hhammoud01** [comment]
It worked !!! But I don't understand why, although in the first "echo %PATH%" it outputs the directory of makensis :/

**Comment by null9beta** [comment]
my only guess would be that there might have been a typo when you where setting the global path and assigning the path again fixed it.

can you compare both echo outputs.

**Comment by hhammoud01** [comment]
They are the same :P hahaa lol :P

**Comment by hhammoud01** [comment]
thanks for the help. Issue fixed

**Comment by stefanjudis** [comment]
:tada: Thanks @null9beta. :)

**Comment by Frondor** [comment]
I'm null at windows as well, but I need to deal with this problem.I don't know what to do with, even if I write `echo %path%` in cmd.exe it prints the whole list of paths, but what should I write after `set=%PATH%` ? The whole list? Just a single path?

    echo %PATH%;
    set PATH=%PATH%;C:\...
    echo %PATH%;
