### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by xcoderzach** [loopline-systems/electron-builder#3]
have you guys come up with a solution to updating windows electron shell apps after they're installed?

**Comment by stefanjudis** [comment]
Not yet... For now prio is to increase test coverage.

But we'll tackle this sooner or later. 
Ideas or infos are more than welcome. :)

**Comment by justinmchase** [comment]
I've been working on this project for updates :smile: 
https://www.npmjs.com/package/electron-updater

**Comment by stefanjudis** [comment]
Nice!!!

@justinmchase So I think we can close this one and refer to your project, right?

**Comment by justinmchase** [comment]
You could. This project is new so it may not be perfect yet, but it seems to be complimentary to this one. I would appreciate any scrutiny and contributions are welcome.

**Comment by stefanjudis** [comment]
Yeah let's do it like that. :)

Currently the updates are not prio, but I'd love to build up a family of `electron-packager`, `electron-builder` and `electron-updater`. :bowtie:

**Comment by xcoderzach** [comment]
@justinmchase That's amazing, you're a lifesaver!  I'm going to use it and if I run into any issues I'll contribute them back.

**Comment by justinmchase** [comment]
@xcoderzach Take a look at the issues, there are a few features not yet implemented. If any of those are blocking you let me know.

**Comment by stefanjudis** [comment]
@justinmchase @xcoderzach Great to see this going guys! :+1:
