### ISSUE TITLE
Wrong Shortcut Icon after building on windows

### ISSUE THREAD

**Issue by hhammoud01** [loopline-systems/electron-builder#30]
Hello,

After successfully building on windows, I get the wrong shortcut icon for the application. The icon of the application is the same as the one I assigned from the config file; but that of the shortcut of the application is an atom picture. (logo of atom electron). When I enter the properties of that shortcut (or any shortcut I create from the original application file then change icon, I get the correct one (This means that the actual icon showing is an atom icon, different from that showing in the properties of that shortcut).
A few more notes:
- When the user uses copy/paste from the original application with the correct icon, the icon stays the same.
- The properties of that shortcut showing in resource hacker are the correct ones. (Although the shortcut has the wrong atom icon)
- Any shortcut that is created from the original exe file has also the wrong icon. 

Any help is appreciated.

**Comment by hhammoud01** [comment]
The bug from windows I guess, I tried it on another version of windows and it worked.

**Comment by miaolq** [comment]
I got this problem too.

**Comment by champ3oy** [comment]
i have this problem too, please is there a fix for it?
