### ISSUE TITLE
Icon problem After installing on windows from created installer: 

### ISSUE THREAD

**Issue by hhammoud01** [loopline-systems/electron-builder#32]
Issue is for WINDOWS 7: Icon shortcut is electron not my app's icon (my app is called anghami)
The exe in Program Files looks fine
If u look in the description of that file (bottom of that window) u can see electron icon which is not the case
If u look at shortcuts they have electron icon
Finally if u look at the output of resource hacker it shows Anghami's icon and not electron's icon

My config.json:

{
  "osx" : {
    "title": "Anghami",
    "background": "desktop.png",
    "icon": "anghami-white.png",
    "icon-size": 128,
    "contents": [
      { "x": 438, "y": 10, "type": "link", "path": "/Applications" },
      { "x": 192, "y": 10, "type": "file" }
    ]
  },
  "win" : {
    "title" : "Anghami",
    "icon" : "assets/IconAnghami.ico"
  }
}

My package.json:

{
  "name"    : "anghami",
  "productName": "Anghami",
  "version" : "0.1.0",
  "main"    : "main.js"
}

files used: 
icons and pictures inside the assets folder, a main javascript file (main.js) and the preloader (preload.js), config.json (above), index.html (background image for the app), package.json (shown above).

packaging command used:
electron-packager ./assets/ Anghami --platform=win32 --arch=ia32 --icon=./assets/IconAnghami.ico --version=0.33.0 --overwrite

building command used:
electron-builder ./Anghami-win32-ia32/ --platform=win --out=./output --config=./assets/config.json

on a final note, after performing the packaging, the icon is CORRECT and nothing is wrong with any shortcut I make out of the exe file. So I think the problem is from the builder.

The output of the two commands seem fine (see attached images).

node version: 0.12.7
npm version: 2.11.3

Obviously I am on a windows 7 32 bit machine.
![output1](https://cloud.githubusercontent.com/assets/14010745/10017725/8619e148-6139-11e5-8dac-b2209cb37848.PNG)
![output2](https://cloud.githubusercontent.com/assets/14010745/10017726/88e14768-6139-11e5-877b-1cd3e55e0d01.PNG)

Thank you for your time.

**Comment by stefanjudis** [comment]
When filing an issue please include as much info as possible:

- `package.json`
- `packager.json`
- files eventually used
- log file
- system information ( node version, npm version, wi/mac/linux )

Thanks for the screenshot, but I can't say anything about that.

**Comment by hhammoud01** [comment]
Edited

**Comment by stefanjudis** [comment]
Another note - please don't use `wtf` when filing issues on an open source project, this sounds really rude and won't speed up getting any help.

And when you paste code please wrap code block inside of three back ticks - so that it becomes readable.

Have you tried another icon, does this work?

I'm not sure I get the problem completely.
The exe inside of `program files` looks okay, but the shortcuts doesn't?

**Comment by hhammoud01** [comment]
The exe in PF looks fine
If u look in the description of that file (bottom of that window) u can see electron icon which is not the case
If u look at shortcuts they have electron icon
Finally if u look at the output of resource hacker it shows Anghami's icon and not electron's icon

Thanks

**Comment by stefanjudis** [comment]
> Have you tried another icon, does this work?

Same behavior for any icon?

**Comment by hhammoud01** [comment]
Yup, same behavior on any icon

**Comment by stefanjudis** [comment]
i'm not sure if I can help here right now.

I'm currently more than busy and I've got no windows machine at hand.
Feel free to ping after next week wednesday.

Unfortunately I have to say, that you have to dig yourself in https://github.com/loopline-systems/electron-builder/blob/master/templates/installer.nsi.tpl. sorry.

**Comment by hhammoud01** [comment]
It's okay. It is worth noting that this is not the case for windows 8 and windows 10, so it is probably a bug from the code that has to do with the platform itself ? I don't know so any suggestion is appreciated.

**Comment by stefanjudis** [comment]
> I don't know so any suggestion is appreciated.

Ja suggestion is to dig and edit

https://github.com/loopline-systems/electron-builder/blob/master/templates/installer.nsi.tpl

-> try and error the shortcut creation,

Good luck.

**Comment by hhammoud01** [comment]
I have tries a lot with the file, did not work,
any thoughts ? :/

**Comment by stefanjudis** [comment]
Maybe you want to list what you tried? 
I haven't have a deeper look into that yet.

**Comment by hhammoud01** [comment]
Since I do not see any platform specific code, I tried different things, including renaming my icon file to icon.ico, changing the size of the icon did not work.
I tried these because that is not a problem on windows 8 or 10.

**Comment by stefanjudis** [comment]
Did you check NSIS docs and bug tracker?
I can't believe that we're the only people having this problem...

**Comment by hhammoud01** [comment]
no i did not check that, reason is that I am not a windows user and I had some problems to understand how to install NSIS on windows. How do I check that anyways ?

**Comment by stefanjudis** [comment]
Googling? :bowtie: 

Maybe http://sourceforge.net/p/nsis/bugs/ includes something releated, too...

**Comment by stefanjudis** [comment]
I Just tried it on Windows 7. And still can't reproduce your problem.

![bildschirmfoto 2015-10-01 um 11 26 56](https://cloud.githubusercontent.com/assets/962099/10217371/9c6a3cd4-682f-11e5-8100-a80e2bedbd1a.png)

**Comment by stefanjudis** [comment]
@hhammoud01 any news here?

**Comment by stefanjudis** [comment]
Closed due to inactivity.
