### ISSUE TITLE
Can't open output file

### ISSUE THREAD

**Issue by halink0803** [loopline-systems/electron-builder#38]
I have tried to use Electron Builder to build Windows installer. However, I just can build one time, but when I install it throws error:

![error](http://i.imgur.com/QmlTHj2.jpg)

I tried to build it again, but this time it throws error:

    makensis: 
    Output: "\Users\hoangha\HaLink\service-oriented-architecture-assignment\desktopApp\~Desktop\\SOA Library Setup.exe"

    makensis: Can't open output file
    Error - aborting creation process

    Finished makensis with code 1
    /usr/local/lib/node_modules/electron-builder/cli.js:30
        throw error;
              ^
    Error: makensis failed
        at ChildProcess.<anonymous> (/usr/local/lib/node_modules/electron-builder/lib/win.js:81:26)
        at ChildProcess.emit (events.js:110:17)
        at maybeClose (child_process.js:1015:16)
        at Socket.<anonymous> (child_process.js:1183:11)
        at Socket.emit (events.js:107:17)
        at Pipe.close (net.js:485:12)

And here is my config.json file:

    {
      "osx" : {
        "title": "SOA Library",
        "background": "assets/osx/installer.png",
        "icon": "assets/osx/mount.icns",
        "icon-size": 80,
        "contents": [
          { "x": 438, "y": 344, "type": "link", "path": "/Applications" },
          { "x": 192, "y": 344, "type": "file" }
        ]
      },
      "win" : {
        "title" : "SOA Library",
        "icon" : "icon.ico"
      }
    }

Do anybody know how to solve this problem? Where did I do wrong.

**Comment by stefanjudis** [comment]
It looks like you build the application including `electron-packager` inside of your actual application executable.

> Be careful not to include node_modules you don't want into your final app. electron-packager, electron-prebuilt and .git will be ignored by default. You can use --ignore to ignore files and folders, e.g. --ignore=node_modules/electron-packager or --ignore="node_modules/(electron-packager|electron-prebuilt)"

Can you check your settings for `electron-packager` and make sure, you do not include these `electron` modules in your application.

I assume you're on a different OS then windows?

**Comment by halink0803** [comment]
Thank you. It helped. I build it on OSX not in Windows.
