### ISSUE TITLE
Support windows?

### ISSUE THREAD

**Issue by justinmchase** [loopline-systems/electron-builder#4]
We are interested in using this project for building installers for our app. You mention on the readme to volunteer to help with this, so here I am :)

Specifically I would like to be able to run the installers on linux, so they can be built while running in travis and ideally windows also. I can contribute and help run, I also have appveyor for windows builds going so I can test it in a CI build.

Any direction to get started would help.

**Comment by stefanjudis** [comment]
Sorry for late reply, had a busy day at work.

But thanks a lot for you jumping in!!! :bowtie:

**Comment by stefanjudis** [comment]
Fixed by #5
