### ISSUE TITLE
Error opening file for writing in windows

### ISSUE THREAD

**Issue by NetanelBasal** [loopline-systems/electron-builder#44]
I make a simple build in OSX to windows EXE and when i try to run this on windows i get this error when installing, even with admin access:

![Image error](http://s21.postimg.org/46o3cmmon/Screen_Shot_2015_10_09_at_17_16_43.png)

**Comment by stefanjudis** [comment]
Hey, please follow the contribution guidelines when reporting issues.

https://github.com/loopline-systems/electron-builder/blob/master/CONTRIBUTING.md

And can you please check if the solution for #38 also helps you?

**Comment by NetanelBasal** [comment]
The installing pass, but the application does not work:
1. The shortuct in the desktop appear without the icon.
2. The EXE file does not exists in the c:/programfiles/appFolder folder

**Comment by stefanjudis** [comment]
> Hey, please follow the contribution guidelines when reporting issues.

**Comment by stefanjudis** [comment]
Closed due to inactivity.
