### ISSUE TITLE
Add ability to specify your own installer.nsi.tpl

### ISSUE THREAD

**Issue by vxsx** [loopline-systems/electron-builder#50]
If i want my app on windows to run only as admin i would need to add 
```
WriteRegStr HKLM "Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" \
                   "$INSTDIR\${APP_NAME}.exe" "RUNASADMIN"
```
to the installer.nsi, but at the moment it's only possible to do by modifying the template file inside of the module.
It would be great to have a possibility to specify a path to your own template to be able to make any customisations you want.

If you're interested in this functionality I'll be able to submit a PR around the weekend.

**Comment by stefanjudis** [comment]
Sounds great - I'd love to take a pr solving this. As this is solving another issue into the list. :)

Thx.
