### ISSUE TITLE
More info on osx.contents

### ISSUE THREAD

**Issue by aaronfrost** [loopline-systems/electron-builder#55]
I would like to dive deeper into the `config.osx.contents` stuff, but I can't find where to read about additional options to put in there. Like I would like to change the zoom of the window, and things of that nature. Any ideas on where I can go for help on this?

**Comment by aaronfrost** [comment]
Not sure how to add the "question" label. Sorry.

**Comment by aaronfrost** [comment]
I found the content I wanted on appdmg's repo. https://www.npmjs.com/package/appdmg

**Comment by stefanjudis** [comment]
@aaronfrost 

Can you maybe update the readme, so that people won't struggle in the future?

**Comment by aaronfrost** [comment]
Definitely. I will submit a PR. Thank you!!!!!!

**Comment by stefanjudis** [comment]
I have to thank you. :P
