### ISSUE TITLE
Add example application

### ISSUE THREAD

**Issue by Frondor** [loopline-systems/electron-builder#56]
I've been struggling with windows' build/packaging processes for days! Finally I managed to package the app (note the use of `rimraf` instead of `rm --rf` because it wasn't working, someone should make a PR for it), the installer gets built but the application itself always run `/default_app` instead of my real `/app` (although I want to use asar technology and by the way, I don't know how because I don't understand the readme.md file, and there is no example written about it).
The installed app also doesn't properly start. I can see its process after some seconds but it never starts.

Just in case, I'm running this on windows 7 x86.

**Comment by stefanjudis** [comment]
Please follow:

https://github.com/loopline-systems/electron-builder/blob/master/CONTRIBUTING.md

> (note the use of rimraf instead of rm --rf because it wasn't working, someone should make a PR for it)

This is open source - so want to take the action?

**Comment by Frondor** [comment]
Never did a pull request before :) I don't want to screw anything up.
I've noted that window's support for this project is really limted, and it still need a lot of coding/documentation to do, like that about `rm --rf`. I was also hitting my head against the wall because I was getting [this](https://i.gyazo.com/e03cdbf1e1fa7c7192f0ec2c968b274b.png) error, which resulted to be part of a mistake of mine, when I changed 

    "pack:win": "npm run build:win && electron-builder \"dist/win/Loopline Systems-win32\" --platform=win --out=\"dist/win\" --config=packager.json"
to 

    "pack:win": "npm run build:win && electron-builder \"dist/win/Loopline Systems\" --platform=win --out=\"dist/win\" --config=packager.json"

the `-win32` part of the "app name" was needed in order to make it work.
In my opinion, that `-win32` part of the name shouldn't be mandatory, it should be "hardcoded" directly in [installer.nsi.tpl](https://github.com/loopline-systems/electron-builder/blob/master/templates/installer.nsi.tpl#L41) as `File /r "<%= appPath %>-win32\*` or something like that.

Now I'm trying that my application executes the real app, instead of the default_app... But I think that's an actual bug of electron 0.33

**Comment by stefanjudis** [comment]
> In my opinion, that -win32 part of the name shouldn't be mandatory, it should be "hardcoded" directly in installer.nsi.tpl as File /r "<%= appPath %>-win32\* or something like that.

Nope, don't agree. That's the path you want to create the installer for. If you're using a wrong path it's not the fault of `electron-builder`.

> Never did a pull request before :) I don't want to screw anything up.
> I've noted that window's support for this project is really limted, and it still need a lot of coding/documentation to do, like that about rm --rf. 

I'm pretty sure, when you keep the right tone and be friendly every open source maintainer (myself included) will help you and guide you through a PR.

Just in case you didn't all of my last comment because I edited it.

> I've been struggling with windows' build/packaging processes for days!

This is not the way to open an issue.

**Comment by stefanjudis** [comment]
I'm closing here, feel free to reopen.

**Comment by Frondor** [comment]
The `!` are not intended for anything but expressing my pain. I'm not forcing anyone to fix it for me, I'm just trying to notify something which isn't working for me, and making a suggestion just in case someone **who knows** (because I don't) can fix it, or at least help me.
A sample app would be nice because everyone can start from there.
I would make a pull request with a sample app, but mine isn't working! I can package the app with no problem but when I execute it, Electron does show the default_app, instead of my app.
Once again, I'm still suggesting a simple "Hello World!" sample app :smile:

**Comment by stefanjudis** [comment]
> The ! are not intended for anything but expressing my pain.

Well... I'd be careful with that. Asking people for help with `!` doesn't work really well. ;)

A sample app is on the roadmap, but that's really hard to achieve it cross platform.

If you could follow this ( another thing when opening issues ):

https://github.com/loopline-systems/electron-builder/blob/master/CONTRIBUTING.md

I can try to help.
