### ISSUE TITLE
Grunt plugin?

### ISSUE THREAD

**Issue by antelle** [loopline-systems/electron-builder#62]
Great tool, thanks :+1: 
Are there any grunt plugins for this?

**Comment by stefanjudis** [comment]
Nope, not yet. :)

Shouldn't take long to put one together... Feel free to go ahead if you need it quickly. :bowtie:

**Comment by antelle** [comment]
Yes, it's pretty easy. I've created it [here](https://github.com/antelle/keeweb/blob/master/grunt/tasks/grunt-electron-builder.js), would you mind if I publish it to npm, or you will create one yourself later?
There's already a package [grunt-electron-builder](https://www.npmjs.com/package/grunt-electron-builder) but it's totally different and it doesn't work for me at all.

**Comment by stefanjudis** [comment]
> Yes, it's pretty easy. I've created it here, would you mind if I publish it to npm, or you will create one yourself later?

No sure - go ahead. If you want to maintain it in future it sounds awesome to me.

> There's already a package grunt-electron-builder but it's totally different and it doesn't work for me at all.

Maybe we want to quickly chat with the person? This looks like a horrible name collision here. And maybe we can work around that somehow without having kind of same samed packages on npm.

What would be you preferred name btw? 

Thanks. :)

**Comment by antelle** [comment]
When I've found that [grunt-electron-builder](https://github.com/Art2B/grunt-electron-builder), I thought, it was for your project. That would be the best name for it. But I'm not sure about their plans. That project has 0 stars, 0 forks and was last updated 3 months ago, the author might have lost interest in it. I think yes, it's better to write them and ask to rename it.

**Comment by stefanjudis** [comment]
> When I've found that grunt-electron-builder, I thought, it was for your project. That would be the best name for it. But I'm not sure about their plans. That project has 0 stars, 0 forks and was last updated 3 months ago, the author might have lost interest in it. I think yes, it's better to write them and ask to rename it.

Jap, exactly... :) Let's check that first. Thanks for jumping in.

**Comment by stefanjudis** [comment]
@antelle 

any news here. I'm closing this one for now - but feel free to reopen. :)

**Comment by havenchyk** [comment]
Hey @stefanjudis, JFI, since there is no response from the author of grunt-electron-builder, I've published [grunt-electron-builder-wrapper](https://www.npmjs.com/package/grunt-electron-builder-wrapper)

**Comment by stefanjudis** [comment]
You waited 18h? That's not that long. ;)

Ja but sure - go ahead. If you want to add `grunt-electron-builder-wrapper` to the readme here please feel free to add via PR.

I can also have a look it at it if you wish - when it's up and running. :)

**Comment by havenchyk** [comment]
Yep, but i haven't time to wait, so published it with another name.  Thanks for you quick response and possible help, i really appreciate it.

**Comment by stefanjudis** [comment]
> Yep, but i haven't time to wait, so published it with another name. 

Just to keep quality of npm packages high in the future. You're aware of the fact the you can install any git repo with npm?

Usually there is no need of publishing anything that is not ready yet ( e.g. your package is lacking a readme ) ;)

But anyways - sure. Wif you have troubles let me know. :)

**Comment by antelle** [comment]
So now we have two unsupported grunt plugins?  😞 
This issue is still open since Feb.19 https://github.com/havenchyk/grunt-electron-builder-wrapper/issues/6

**Comment by havenchyk** [comment]
I'll take a look, @antelle thanks for pushing

**Comment by antelle** [comment]
@havenchyk  thank you! 
You should just remove `.init()` and replace callback with a promise.
