### ISSUE TITLE
Building on windows - nsis not found 

### ISSUE THREAD

**Issue by nicksmetBagaar** [loopline-systems/electron-builder#66]
hello,

I'm making a windows only app for the first time. I'm building with this command : 
electron-builder \"dist/win/somename-win32-ia32\" --platform=win --out=\"dist/win\" --config=packager.json

But it keeps failing on nsis. Nsis is correctly installed. What can I do to fix this ?
this is my packager.json file : 
  {
  "osx" : {
    "title": "SomeName",
    "background": "assets/osx/installer.png",
    "icon": "assets/osx/mount.icns",
    "icon-size": 80,
    "contents": [
      { "x": 438, "y": 344, "type": "link", "path": "/Applications" },
      { "x": 192, "y": 344, "type": "file" }
    ]
  },
  "win" : {
    "title" : "SomeName",
    "icon" : "assets/win/icon.ico"
    }
  }

  - Running electron-builder 2.1.1
  - Starting creation of installer for ´win
  - makensis not found.
  Please install "nullsoft scriptable install system"
  http://nsis.sourceforge.net/Download

  C:\Users\nick smet\AppData\Roaming\npm\node_modules\electron-builder\cli.js:30
    throw error;
    ^

  Error: makensis failed
    at ChildProcess.<anonymous> (C:\Users\nick smet\AppData\Roaming\npm\node_modules\electron-builder\lib\win.js:74:26)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by stefanjudis** [comment]
hey, is the `makensis` command available in your command line?

**Comment by nicksmetBagaar** [comment]
No it isn't. I tried setting the PATH variable like suggested in another thread. But no luck so far

**Comment by stefanjudis** [comment]
I'm not sure, that we can help with this one, as it is connected to your environment and the `makensis` command is mandatory for `electron-builder` to work.

Sorry. :(

Feel free to reopen.
