### ISSUE TITLE
Support build on linux

### ISSUE THREAD

**Issue by stefanjudis** [loopline-systems/electron-builder#7]
Follow up of #4.

**Comment by s-a** [comment]
:+1:

**Comment by hotrush** [comment]
:+1:

**Comment by stefanjudis** [comment]
https://github.com/loopline-systems/electron-builder/pull/14

That's the current state. :)

**Comment by joeferraro** [comment]
@stefanjudis are you waiting for @justinmchase's PR to be migrated and implemented into `appdmg` before progressing on this side?

**Comment by stefanjudis** [comment]
@joeferraro 

Ja, kind of. Because `appdmg` might be the better place to implement the support. What do you think?

**Comment by cha55son** [comment]
+1 I am currently trying to build for Linux/Mac/Win on a linux machine.

**Comment by justinmchase** [comment]
Can someone on the appdmg team take it from here? I'm out of time on this one and I think we're going to be building installers on each platform for itself.

**Comment by cha55son** [comment]
This works for me on Linux. We've already incorporated it into our build process. I would love to see this make it's way back into the main line.

**Comment by justinmchase** [comment]
Maybe just take this PR for now and then if `appdmg` project implements the missing features you can pull it back out?

**Comment by championswimmer** [comment]
Are we able to build .deb with this as of now ?

**Comment by stefanjudis** [comment]
Nop - haven't tried that yet and is not implemented. sorry.

**Comment by championswimmer** [comment]
Cool, that allows me the opportunity to come with a pull request then. :)

**Comment by stefanjudis** [comment]
Sounds awesome!!!

**Comment by stefanjudis** [comment]
Closed because of more detailed solution here:

https://github.com/loopline-systems/electron-builder/issues/75
