### ISSUE TITLE
Default screen when building app

### ISSUE THREAD

**Issue by dietlev** [loopline-systems/electron-builder#70]
Hey all,

I created a small app using Electron, which is working just fine.
However, when I try to build it, I get some weird results.

The building itself works fine, but when I open the .app, I see the "Welcome to Electron" title instead of the app.

![screen shot 2015-11-19 at 11 02 07](https://cloud.githubusercontent.com/assets/868055/11267680/0886673c-8ead-11e5-8a26-2b3736b170e4.png)

I created a repo here with just the basic files, and I get the same results:
https://github.com/dietlev/electron-build-demo

I'm on 
`OS X 10.10.5`
`node v5.1.0`
`npm 3.4.0`

Am I missing something here?
Thanks in advance

**Comment by stefanjudis** [comment]
@dietlev 

Still having problems here?
Will have a look at it today - if so. :bowtie:

**Comment by dietlev** [comment]
Good morning ( in Belgium )
Yes, I still have the same issue. My app is finished, just the building part is not working properly.

Thanks in advance :)

**Comment by stefanjudis** [comment]
Cool. :+1: 

But I shall still check https://github.com/dietlev/electron-build-demo ?

**Comment by dietlev** [comment]
Yes, if that's working I can see where the actual app is going wrong

**Comment by stefanjudis** [comment]
okidoki. :+1: I'll have a look around 1pm. :)

**Comment by stefanjudis** [comment]
@dietlev 

The problem appears already in `electron-packager`, right?
That's what I noticed - point is that you're missing a `package.json` in your `app` folder.

From the electron docs.

> Main Process
> In Electron, the process that runs package.json's main script is called the main process. The script that runs in the main process can display a GUI by creating web pages.

So with this `package.json` in root ( I updated also electron-packager )

```
{
  "name": "ElectronTest",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "dev": "electron ./app",
    "clean": "rm -rf ./dist",
    "clean:osx": "rm -rf ./dist/osx",
    "clean:win": "rm -rf ./dist/win",
    "build": "npm run clean && npm run build:osx && npm run build:win",
    "build:osx": "npm run clean:osx && electron-packager ./app LooplineSystems --out=dist/osx --platform=darwin --arch=x64 --version=0.25.3 --icon=assets/osx/loopline.icns",
    "pack": "npm run pack:osx && npm run pack:win",
    "pack:osx": "npm run build:osx && electron-builder \"dist/osx/LooplineSystems-darwin-x64/LooplineSystems.app\" --platform=osx --out=\"dist/osx\" --config=packager.json"
  },
  "dependencies": {
    "electron-builder": "^2.0.0",
    "electron-packager": "^5.0.0",
    "electron-prebuilt": "^0.35.0"
  }
}
```

and this dummy `package.json` in app folder

```
{
  "name": "app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "MIT"
}
```

your demo app in development, the `.app` and `.dmg` run fine. 

I'm closing here - feel free to reopen if you have still troubles.
