### ISSUE TITLE
Add Linux .deb and .rpm support using FPM

### ISSUE THREAD

**Issue by etiktin** [loopline-systems/electron-builder#75]
There's an awesome project called [FPM](https://github.com/jordansissel/fpm) that allows you to generate .deb and .rpm packages.

It's written in Ruby, so users will need to install it on their own, but that's already the case for NSIS.

There's an Electron starter project that already uses it, called [Electron SuperKit](https://github.com/Aluxian/electron-superkit). Here's how they are using FPM: https://github.com/Aluxian/electron-superkit/blob/master/tasks/pack.coffee#L69-L116
There's also a basic grunt task that uses it, at: https://www.npmjs.com/package/grunt-fpm-package

A general guide on FPM can be found at: https://www.digitalocean.com/community/tutorials/how-to-use-fpm-to-easily-create-packages-in-multiple-formats

What do you think about using it for packaging apps for the Linux platform?

**Comment by stefanjudis** [comment]
Sure - I haven't had the time to check the projects in detail - but supporting linux packages sounds awesome. :+1:

**Comment by tborychowski** [comment]
+1

**Comment by xseignard** [comment]
Hello,
Here is what I do, inspired from superkit, but maybe with less noise, and less features, but still! And no coffee!

https://gist.github.com/xseignard/fbf9e222fb3db8bb9f48

Hope this helps

**Comment by stefanjudis** [comment]
@xseignard I'd be more than open for a PR. :)

**Comment by xseignard** [comment]
See #123

**Comment by stefanjudis** [comment]
I think we can close this as #123 landed and continue with more specific issues. 

Thanks for the work. :)

**Comment by etiktin** [comment]
Thank you guys. This is awesome!

**Comment by xseignard** [comment]
Hello @etiktin,

Glad you like it! This is a first version, and feedback will be very welcome ;)

Regards
