### ISSUE TITLE
Difference between electron-builder and grunt-electron-installer

### ISSUE THREAD

**Issue by havenchyk** [loopline-systems/electron-builder#89]
Hi, I haven't found in the readme any difference between this package and [atom/grunt-electron-installer](https://github.com/atom/grunt-electron-installer)

Could you please describe the differences for people who wouldn't like to compare sources of two packages?

**Comment by stefanjudis** [comment]
Sure we might wanna do that.

In short afaik:

- `grunt-electron-installer` has a hard grund dep | we have no hard build system dep
- `grunt-electron-installer` only creates windows installers | we create windows and mac installers
- `grunt-electron-installer` works only on windows | we work cross platform
- `grunt-electron-installer` uses squirrel for creating | we use nsis but might wanna support `squirrel`in future too

**Comment by havenchyk** [comment]
@stefanjudis great, thanks, this should be in readme! 

`offtop` since you're not using squirrel, is it possible to make autoupdates working with installer, provided by electron-builder?

**Comment by stefanjudis** [comment]
> offtop since you're not using squirrel, is it possible to make autoupdates working with installer, provided by electron-builder?

pretty sure it is - haven't tried it yet though.

But in my head is definitely provide squirrel option too here.

**Comment by havenchyk** [comment]
Great, thank you. Let's leave this issue since we need some changes in readme before closing, I guess :smile:

**Comment by stefanjudis** [comment]
well... feel free to bring it in. :)

**Comment by havenchyk** [comment]
Probably can be closed. @stefanjudis
