### ISSUE TITLE
Exception during running the command from another folder

### ISSUE THREAD

**Issue by havenchyk** [loopline-systems/electron-builder#92]
Hi, during running the script not from the folder where electron is located, I've got 

```
makensis: File: "path\to\my\app\*" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "/tmp/1hyau9no6zxccgo88o8wo.tpl" on line 59 -- aborting creation process
```

Could you @stefanjudis assist to find the correct place where fix should be added?

**Comment by havenchyk** [comment]
The first issue was on linux, the same i've got on windows today.

`makensis: File: "Client\myapp-win32-x64\*" -> no files found.`

BTW, the path should be `client\myapp-win32-x64\`, where first *c* is small, but stack prints me capitalized value.

**Comment by stefanjudis** [comment]
Which `electron-builder` version are you on?

I had a fix about this recently.

**Comment by havenchyk** [comment]
I believe I'm on the latest version.

```
"version": "2.4.0"
```

**Comment by stefanjudis** [comment]
Hmm, the path is coming from here.

https://github.com/loopline-systems/electron-builder/blob/master/cli.js#L34

Maybe you could dig a bit or provide me your detailed config so that I can have a look. :)

**Comment by havenchyk** [comment]
@stefanjudis I found the "normalization" [here](https://github.com/loopline-systems/electron-builder/blob/master/lib/win.js#L33). It explains the problem with linux, but not with windows.

**Comment by stefanjudis** [comment]
If you provide me your config I can have a look tonight.

**Comment by havenchyk** [comment]
Sure, I'll provide it later. 

BTW, relative path is not working, but with absolute path for appPath everything works fine (after removing `_windowsify`, of course.

**Comment by stefanjudis** [comment]
@havenchyk what the state here?

Can you please provide your configs and commands?

**Comment by havenchyk** [comment]
@stefanjudis config is the same like you're using in the readme:

`electron-builder \"dist/osx/Loopline Systems.app\" --platform=osx --out=\"dist/osx\" --config=builder.json"`

But, I pass this config not via cli.js, but directly to the builder.build, so after `_windowsify` on appPath, the path is broken.

I can provide PR for it if you would like.

**Comment by stefanjudis** [comment]
> But, I pass this config not via cli.js, but directly to the builder.build, so after _windowsify on appPath, the path is broken. 

I don't get that - you're requiring a file that is not public?

**Comment by havenchyk** [comment]
@stefanjudis I'm using electron-builder in the grunt-electron-builder-wrapper. What I do - is 

```js
var electronBuilder = require('electron-builder').init();
...

electronBuilder.build(options);
```

And options have `appPath`. You've fixed similar issue about a week ago, but only in the cli.js

**Comment by stefanjudis** [comment]
Mmmmh... I see... Sorry - forgot about the grunt counterpart. And forgot that `index.js` is also exposed ( the project is lacking documentation for that too ).

but there shouldn't be the need to fix it in several places - the installers itself ( `osx` & `win` ) should get the correct paths provided?

`appPath` should get an absolute path when it's hitting these files.
Or what do you think?

**Comment by havenchyk** [comment]
I think, that this check should be made inside the `osx & win` for now, look at https://github.com/loopline-systems/electron-builder/blob/master/lib/win.js#L33 if you're on windows, it's ok, but if you're on mac or linux, it's not needed to `_windowsify` the path. 

Also I think that user of the module should be able to pass relative path as well. So we need to do additional check for win and mac:
- is the appPath absolute?
- if not, make path.resolve
- if windows - invoke `_windowsify` (if it's really needed)

**Comment by stefanjudis** [comment]
>  it's ok, but if you're on mac or linux, it's not needed to _windowsify the path.

I needed it in first place and I am on a mac - so I'm not sure about that.

> Also I think that user of the module should be able to pass relative path as well

Totally agree on that one. But that doesn't mean we have to treat it in `win.js` or `osx.js`. These two files should only accept absolute paths and do there thing with it. We're also avoiding code duplication for path handling. 

So about the points:

> is the appPath absolute?

This can be done by simply using `path.resolve` - there is no additional check needed as it's doing that. :)

```
path.resolve( path.cwd(), '/Users' )
> /Users

path.resolve( process.cwd(), 'foo' )
> /Users/stefan/Sites/perf-tooling/foo
```

> if windows - invoke _windowsify (if it's really needed)

I really would like to double check that. Are you on a mac to prove it?

**Comment by havenchyk** [comment]
I'm can check only on windows and linux. I'm mostly working on linux, so it was an issue for me.

**Comment by stefanjudis** [comment]
> I can check only on windows and linux. I'm mostly working on linux, so it was an issue for me.

Well then PR it - and I'll check it. :)

> BTW, if you're on Mac and need _windowsify, there is some misleading in the name.

Well not really - because it will go into wine and NSIS and these want windows paths. :)
