### ISSUE TITLE
Improve documentation for makensis

### ISSUE THREAD

**Issue by havenchyk** [loopline-systems/electron-builder#94]
Hi, I've installed nsis for windows, but still get 

```
- makensis not found.
  Please install "nullsoft scriptable install system"
  http://nsis.sourceforge.net/Download
```
Should I add it also to path?

**Comment by havenchyk** [comment]
I found #29, can we add this info in the readme probably in the troubleshooting section?

**Comment by stefanjudis** [comment]
@havenchyk please do. :+1: :)

**Comment by stefanjudis** [comment]
@havenchyk Any chance to get a PR for that?

**Comment by havenchyk** [comment]
@stefanjudis pr is ready by @mkaz
