### ISSUE TITLE
confusing readme

### ISSUE THREAD

**Issue by tborychowski** [loopline-systems/electron-builder#96]
the example `scripts` part of the `package.json` is a bit confusing:
```json
{
    "build": "npm run clean && npm run build:osx && npm run build:win",
    "build:osx": "npm run clean:osx && electron-packager ./app \"Loopline Systems\" --out=dist/osx --platform=darwin --arch=x64 --version=0.25.3 --icon=assets/osx/loopline.icns",
    "build:win": "npm run clean:win && electron-packager ./app \"Loopline Systems\" --out=dist/win --platform=win32 --arch=ia32 --version=0.25.3 --icon=assets/win/icon.ico",

    "pack": "npm run pack:osx && npm run pack:win",
    "pack:osx": "npm run build:osx && electron-builder \"dist/osx/Loopline Systems.app\" --platform=osx --out=\"dist/osx\" --config=packager.json",
    "pack:win": "npm run build:win && electron-builder \"dist/win/Loopline Systems-win32\" --platform=win --out=\"dist/win\" --config=packager.json"
}
```
it says `pack` to run `electron-builder` and `build` to use `electron-packager`.
Shouldn't this be reversed?

**Comment by havenchyk** [comment]
Probably, yes. Electron-builder creates installers and electron-packager makes packages. Could you please make PR with a fix?

**Comment by stefanjudis** [comment]
Fixed with https://github.com/loopline-systems/electron-builder/pull/98.

**Comment by tborychowski** [comment]
Here you are: https://github.com/loopline-systems/electron-builder/pull/98
I also updated `packager.json` to `builder.json` to be aligned with the naming convention, but this might be a bit controversial and it seems that the former name might have been used elsewhere too.
If you'd want me to revert the name of this file (in another PR), let me know!
Thanks :-)

**Comment by stefanjudis** [comment]
All good with this one. ;)
