### ISSUE TITLE
add Squirrel for creating windows installer

### ISSUE THREAD

**Issue by stefanjudis** [loopline-systems/electron-builder#99]

**Comment by havenchyk** [comment]
@stefanjudis could you please prepare a roadmap for it? I'd like to help

**Comment by stefanjudis** [comment]
@havenchyk For me this looks like a major rewrite and I'd like to tackle a few things first.

- [ ] adding tests https://github.com/loopline-systems/electron-builder/issues/103
- [ ] make `config.json` optional and read `package.json` too https://github.com/loopline-systems/electron-builder/issues/104
- [ ] splitting the readme's as it's becoming more complex https://github.com/loopline-systems/electron-builder/issues/101

After that it should be pretty straight forward.

https://github.com/Aluxian/electron-windows-installer/tree/master/src

does it already and then we can either use it directly or check what they're doing there. :)

I'd love to have `NSIS` and `Squirrel` included, because people already have it up and running as it is. :)
